//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// **************************************************************************
// * 作者= jjr
// * 创建时间= 2017-4-11
// * 用途= 日常活动协议
// ***************************************************************************

// Generated from: dailyActivityHandler.proto
// Note: requires additional types generated from: common.proto
// Note: requires additional types generated from: dailyActivity.proto
namespace pomelo.area
{
  
  //---------------------------------------------------------------------------------------
  /// <summary>
  /// 获取日常活动列表   （请求）
  /// </summary>
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DailyActivityRequest")]
  public partial class DailyActivityRequest : global::ProtoBuf.IExtensible
  {
    public DailyActivityRequest() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  /// <summary>
  /// 获取日常活动列表  （返回）
  /// </summary>
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DailyActivityResponse")]
  public partial class DailyActivityResponse : global::ProtoBuf.IExtensible
  {
    public DailyActivityResponse() {}
    
    
    private int _s2c_code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"s2c_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int s2c_code
    {
      get { return _s2c_code; }
      set { _s2c_code = value; }
    }
    
    private string _s2c_msg = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"s2c_msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string s2c_msg
    {
      get { return _s2c_msg; }
      set { _s2c_msg = value; }
    }
    
    private readonly global::System.Collections.Generic.List<pomelo.dailyActivity.DailyInfo> _s2c_dailyLs = new global::System.Collections.Generic.List<pomelo.dailyActivity.DailyInfo>();
    /// <summary>
    /// 活动列表
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(3, Name=@"s2c_dailyLs", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pomelo.dailyActivity.DailyInfo> s2c_dailyLs
    {
      get { return _s2c_dailyLs; }
    }
  
    
    private int _s2c_totalDegree = default(int);
    /// <summary>
    /// 总活跃度
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"s2c_totalDegree", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int s2c_totalDegree
    {
      get { return _s2c_totalDegree; }
      set { _s2c_totalDegree = value; }
    }
    
    private readonly global::System.Collections.Generic.List<pomelo.dailyActivity.DegreeInfo> _s2c_degreeLs = new global::System.Collections.Generic.List<pomelo.dailyActivity.DegreeInfo>();
    /// <summary>
    /// 活跃度奖励列表
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(5, Name=@"s2c_degreeLs", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pomelo.dailyActivity.DegreeInfo> s2c_degreeLs
    {
      get { return _s2c_degreeLs; }
    }
  
    
    private int _s2c_weekIndex = default(int);
    /// <summary>
    /// 今天星期几
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"s2c_weekIndex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int s2c_weekIndex
    {
      get { return _s2c_weekIndex; }
      set { _s2c_weekIndex = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  /// <summary>
  /// 领取活跃度奖励  （请求）
  /// </summary>
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetDegreeRewardRequest")]
  public partial class GetDegreeRewardRequest : global::ProtoBuf.IExtensible
  {
    public GetDegreeRewardRequest() {}
    
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  /// <summary>
  /// 领取活跃度奖励  （返回）
  /// </summary>
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetDegreeRewardResponse")]
  public partial class GetDegreeRewardResponse : global::ProtoBuf.IExtensible
  {
    public GetDegreeRewardResponse() {}
    
    
    private int _s2c_code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"s2c_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int s2c_code
    {
      get { return _s2c_code; }
      set { _s2c_code = value; }
    }
    
    private string _s2c_msg = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"s2c_msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string s2c_msg
    {
      get { return _s2c_msg; }
      set { _s2c_msg = value; }
    }
    
    private int _id = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    
    private int _s2c_state = default(int);
    /// <summary>
    /// 奖励领取后状态
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"s2c_state", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int s2c_state
    {
      get { return _s2c_state; }
      set { _s2c_state = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UpdateActivityPush")]
  public partial class UpdateActivityPush : global::ProtoBuf.IExtensible
  {
    public UpdateActivityPush() {}
    
    
    private readonly global::System.Collections.Generic.List<pomelo.dailyActivity.DailyInfo> _s2c_dailyLs = new global::System.Collections.Generic.List<pomelo.dailyActivity.DailyInfo>();
    /// <summary>
    /// 刷新活动列表
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(1, Name=@"s2c_dailyLs", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pomelo.dailyActivity.DailyInfo> s2c_dailyLs
    {
      get { return _s2c_dailyLs; }
    }
  
    
    private int _s2c_totalDegree = default(int);
    /// <summary>
    /// 总活跃度
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"s2c_totalDegree", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int s2c_totalDegree
    {
      get { return _s2c_totalDegree; }
      set { _s2c_totalDegree = value; }
    }
    
    private readonly global::System.Collections.Generic.List<pomelo.dailyActivity.DegreeInfo> _s2c_degreeLs = new global::System.Collections.Generic.List<pomelo.dailyActivity.DegreeInfo>();
    /// <summary>
    /// 活跃度奖励列表
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(3, Name=@"s2c_degreeLs", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pomelo.dailyActivity.DegreeInfo> s2c_degreeLs
    {
      get { return _s2c_degreeLs; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
}
  