//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// ***************************************************************************
// * 作者= 周明凯
// * 创建时间= 2017-12-14
// * 用途= 冲榜处理器
// ***************************************************************************/

// Generated from: activityRevelryHandler.proto
// Note: requires additional types generated from: common.proto
namespace pomelo.revelry
{
  
  //---------------------------------------------------------------------------------------
  /// <summary>
  /// 每一天中的小栏目
  /// </summary>
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RevelryColumnInfo")]
  public partial class RevelryColumnInfo : global::ProtoBuf.IExtensible
  {
    public RevelryColumnInfo() {}
    
    
    private string _id;
    /// <summary>
    /// 编号，用这个编号来取对应的排行数据
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string id
    {
      get { return _id; }
      set { _id = value; }
    }
    
    private string _name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    
    private string _label;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"label", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string label
    {
      get { return _label; }
      set { _label = value; }
    }
    
    private string _goto1 = "";
    /// <summary>
    /// 查看榜单
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"goto1", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string goto1
    {
      get { return _goto1; }
      set { _goto1 = value; }
    }
    
    private string _goto2 = "";
    /// <summary>
    /// 我要变强
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"goto2", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string goto2
    {
      get { return _goto2; }
      set { _goto2 = value; }
    }
    
    private string _tip = "";
    /// <summary>
    /// 提示
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"tip", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string tip
    {
      get { return _tip; }
      set { _tip = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  /// <summary>
  /// 冲榜大类中的每一天
  /// </summary>
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RevelryTodayInfo")]
  public partial class RevelryTodayInfo : global::ProtoBuf.IExtensible
  {
    public RevelryTodayInfo() {}
    
    
    private string _name;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    
    private readonly global::System.Collections.Generic.List<pomelo.revelry.RevelryColumnInfo> _column = new global::System.Collections.Generic.List<pomelo.revelry.RevelryColumnInfo>();
    [global::ProtoBuf.ProtoMember(2, Name=@"column", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pomelo.revelry.RevelryColumnInfo> column
    {
      get { return _column; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  /// <summary>
  /// 冲榜大类
  /// </summary>
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RevelryTabInfo")]
  public partial class RevelryTabInfo : global::ProtoBuf.IExtensible
  {
    public RevelryTabInfo() {}
    
    
    private string _name;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    
    private readonly global::System.Collections.Generic.List<pomelo.revelry.RevelryTodayInfo> _today = new global::System.Collections.Generic.List<pomelo.revelry.RevelryTodayInfo>();
    [global::ProtoBuf.ProtoMember(2, Name=@"today", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pomelo.revelry.RevelryTodayInfo> today
    {
      get { return _today; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  /// <summary>
  /// 兑换配置
  /// </summary>
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"KingExchange")]
  public partial class KingExchange : global::ProtoBuf.IExtensible
  {
    public KingExchange() {}
    
    
    private int _tabId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"tabId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int tabId
    {
      get { return _tabId; }
      set { _tabId = value; }
    }
    
    private string _tabName;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"tabName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string tabName
    {
      get { return _tabName; }
      set { _tabName = value; }
    }
    
    private string _item1code;
    /// <summary>
    /// 兑换获得物品
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"item1code", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string item1code
    {
      get { return _item1code; }
      set { _item1code = value; }
    }
    
    private int _item1num;
    /// <summary>
    /// 兑换获得数量
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"item1num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int item1num
    {
      get { return _item1num; }
      set { _item1num = value; }
    }
    
    private string _item2code;
    /// <summary>
    /// 兑换消耗物品
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"item2code", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string item2code
    {
      get { return _item2code; }
      set { _item2code = value; }
    }
    
    private int _item2num;
    /// <summary>
    /// 兑换消耗数量
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"item2num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int item2num
    {
      get { return _item2num; }
      set { _item2num = value; }
    }
    
    private string _avatarId;
    /// <summary>
    /// 展示模型
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"avatarId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string avatarId
    {
      get { return _avatarId; }
      set { _avatarId = value; }
    }
    
    private string _tip = "";
    /// <summary>
    /// 提示
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"tip", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string tip
    {
      get { return _tip; }
      set { _tip = value; }
    }
    
    private int _showType = default(int);
    /// <summary>
    /// 显示类型
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"showType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int showType
    {
      get { return _showType; }
      set { _showType = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  /// <summary>
  /// 拉取冲榜栏目请求
  /// </summary>
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RevelryGetColumnRequest")]
  public partial class RevelryGetColumnRequest : global::ProtoBuf.IExtensible
  {
    public RevelryGetColumnRequest() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  /// <summary>
  /// 拉取冲榜栏目响应
  /// </summary>
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RevelryGetColumnResponse")]
  public partial class RevelryGetColumnResponse : global::ProtoBuf.IExtensible
  {
    public RevelryGetColumnResponse() {}
    
    
    private int _s2c_code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"s2c_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int s2c_code
    {
      get { return _s2c_code; }
      set { _s2c_code = value; }
    }
    
    private string _s2c_msg = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"s2c_msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string s2c_msg
    {
      get { return _s2c_msg; }
      set { _s2c_msg = value; }
    }
    
    private readonly global::System.Collections.Generic.List<pomelo.revelry.RevelryTabInfo> _info = new global::System.Collections.Generic.List<pomelo.revelry.RevelryTabInfo>();
    [global::ProtoBuf.ProtoMember(3, Name=@"info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pomelo.revelry.RevelryTabInfo> info
    {
      get { return _info; }
    }
  
    
    private readonly global::System.Collections.Generic.List<pomelo.revelry.KingExchange> _exchange = new global::System.Collections.Generic.List<pomelo.revelry.KingExchange>();
    /// <summary>
    /// 兑换展示（如果数组为空，则不显示）
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(4, Name=@"exchange", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pomelo.revelry.KingExchange> exchange
    {
      get { return _exchange; }
    }
  
    
    private int _selectedIndex = default(int);
    /// <summary>
    /// 默认选中的info字段的下标，从0开始
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"selectedIndex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int selectedIndex
    {
      get { return _selectedIndex; }
      set { _selectedIndex = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  /// <summary>
  /// 冲榜排行信息（数组内容参考排行榜）
  /// </summary>
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RevelryRankInfo")]
  public partial class RevelryRankInfo : global::ProtoBuf.IExtensible
  {
    public RevelryRankInfo() {}
    
    
    private readonly global::System.Collections.Generic.List<string> _contents = new global::System.Collections.Generic.List<string>();
    /// <summary>
    /// 玩家或公会的信息数组
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(1, Name=@"contents", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> contents
    {
      get { return _contents; }
    }
  
    
    private readonly global::System.Collections.Generic.List<pomelo.Avatar> _avatars = new global::System.Collections.Generic.List<pomelo.Avatar>();
    /// <summary>
    /// 只有第一名才有此属性
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(2, Name=@"avatars", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pomelo.Avatar> avatars
    {
      get { return _avatars; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  /// <summary>
  /// 排行奖励信息
  /// </summary>
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RevelryAwardInfo")]
  public partial class RevelryAwardInfo : global::ProtoBuf.IExtensible
  {
    public RevelryAwardInfo() {}
    
    
    private string _itemcode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"itemcode", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string itemcode
    {
      get { return _itemcode; }
      set { _itemcode = value; }
    }
    
    private int _itemcount;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"itemcount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int itemcount
    {
      get { return _itemcount; }
      set { _itemcount = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  /// <summary>
  /// 排行配置信息
  /// </summary>
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RevelryConfigInfo")]
  public partial class RevelryConfigInfo : global::ProtoBuf.IExtensible
  {
    public RevelryConfigInfo() {}
    
    
    private int _minRank;
    /// <summary>
    /// 最小排名
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"minRank", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int minRank
    {
      get { return _minRank; }
      set { _minRank = value; }
    }
    
    private int _maxRank;
    /// <summary>
    /// 最大排名
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"maxRank", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int maxRank
    {
      get { return _maxRank; }
      set { _maxRank = value; }
    }
    
    private readonly global::System.Collections.Generic.List<pomelo.revelry.RevelryAwardInfo> _award = new global::System.Collections.Generic.List<pomelo.revelry.RevelryAwardInfo>();
    /// <summary>
    /// 奖励
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(3, Name=@"award", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pomelo.revelry.RevelryAwardInfo> award
    {
      get { return _award; }
    }
  
    
    private pomelo.revelry.RevelryRankInfo _player = null;
    /// <summary>
    /// 上榜玩家
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"player", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public pomelo.revelry.RevelryRankInfo player
    {
      get { return _player; }
      set { _player = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  /// <summary>
  /// 拉取栏目中排行信息请求
  /// </summary>
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RevelryGetRankInfoRequest")]
  public partial class RevelryGetRankInfoRequest : global::ProtoBuf.IExtensible
  {
    public RevelryGetRankInfoRequest() {}
    
    
    private string _id;
    /// <summary>
    /// 编号
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  /// <summary>
  /// 拉取栏目中排行信息响应
  /// </summary>
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RevelryGetRankInfoResponse")]
  public partial class RevelryGetRankInfoResponse : global::ProtoBuf.IExtensible
  {
    public RevelryGetRankInfoResponse() {}
    
    
    private int _s2c_code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"s2c_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int s2c_code
    {
      get { return _s2c_code; }
      set { _s2c_code = value; }
    }
    
    private string _s2c_msg = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"s2c_msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string s2c_msg
    {
      get { return _s2c_msg; }
      set { _s2c_msg = value; }
    }
    
    private int _rankKey;
    /// <summary>
    /// 冲榜专用属性，用来标识是哪个排行榜
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"rankKey", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int rankKey
    {
      get { return _rankKey; }
      set { _rankKey = value; }
    }
    
    private readonly global::System.Collections.Generic.List<pomelo.revelry.RevelryConfigInfo> _config = new global::System.Collections.Generic.List<pomelo.revelry.RevelryConfigInfo>();
    [global::ProtoBuf.ProtoMember(4, Name=@"config", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pomelo.revelry.RevelryConfigInfo> config
    {
      get { return _config; }
    }
  
    
    private pomelo.revelry.RevelryRankInfo _self = null;
    /// <summary>
    /// 自己的信息
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"self", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public pomelo.revelry.RevelryRankInfo self
    {
      get { return _self; }
      set { _self = value; }
    }
    
    private int _selfRank = default(int);
    /// <summary>
    /// 自己的排名
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"selfRank", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int selfRank
    {
      get { return _selfRank; }
      set { _selfRank = value; }
    }
    
    private string _title = "";
    /// <summary>
    /// 第一名送的称号资源
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"title", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string title
    {
      get { return _title; }
      set { _title = value; }
    }
    
    private int _timeleft = default(int);
    /// <summary>
    /// 剩余时间（单位：秒）
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"timeleft", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int timeleft
    {
      get { return _timeleft; }
      set { _timeleft = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  /// <summary>
  /// 冲榜活动兑换请求
  /// </summary>
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RevelryExchangeRequest")]
  public partial class RevelryExchangeRequest : global::ProtoBuf.IExtensible
  {
    public RevelryExchangeRequest() {}
    
    
    private int _id;
    /// <summary>
    /// 兑换配置中的tabId
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    
    private int _num;
    /// <summary>
    /// 兑换数量
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int num
    {
      get { return _num; }
      set { _num = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  /// <summary>
  /// 冲榜活动兑换响应
  /// </summary>
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RevelryExchangeResponse")]
  public partial class RevelryExchangeResponse : global::ProtoBuf.IExtensible
  {
    public RevelryExchangeResponse() {}
    
    
    private int _s2c_code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"s2c_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int s2c_code
    {
      get { return _s2c_code; }
      set { _s2c_code = value; }
    }
    
    private string _s2c_msg = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"s2c_msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string s2c_msg
    {
      get { return _s2c_msg; }
      set { _s2c_msg = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
}
  