//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// ***************************************************************************
// * 作者= 卢松洁
// * 创建时间= 2015-08-27
// * 用途= 聊天处理器
// ***************************************************************************

// Generated from: chatHandler.proto
// Note: requires additional types generated from: common.proto
namespace pomelo.chat
{
  
  //---------------------------------------------------------------------------------------
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SendChatRequest")]
  public partial class SendChatRequest : global::ProtoBuf.IExtensible
  {
    public SendChatRequest() {}
    
    
    private int _c2s_scope;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"c2s_scope", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int c2s_scope
    {
      get { return _c2s_scope; }
      set { _c2s_scope = value; }
    }
    
    private string _c2s_content;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"c2s_content", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string c2s_content
    {
      get { return _c2s_content; }
      set { _c2s_content = value; }
    }
    
    private string _c2s_serverData = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"c2s_serverData", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string c2s_serverData
    {
      get { return _c2s_serverData; }
      set { _c2s_serverData = value; }
    }
    
    private string _c2s_acceptRoleId = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"c2s_acceptRoleId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string c2s_acceptRoleId
    {
      get { return _c2s_acceptRoleId; }
      set { _c2s_acceptRoleId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SendChatResponse")]
  public partial class SendChatResponse : global::ProtoBuf.IExtensible
  {
    public SendChatResponse() {}
    
    
    private int _s2c_code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"s2c_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int s2c_code
    {
      get { return _s2c_code; }
      set { _s2c_code = value; }
    }
    
    private string _s2c_msg = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"s2c_msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string s2c_msg
    {
      get { return _s2c_msg; }
      set { _s2c_msg = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  /// <summary>
  /// 聊天保存消息
  /// </summary>
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetSaveChatMsgRequest")]
  public partial class GetSaveChatMsgRequest : global::ProtoBuf.IExtensible
  {
    public GetSaveChatMsgRequest() {}
    
    
    private int _c2s_scope;
    /// <summary>
    /// 频道
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"c2s_scope", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int c2s_scope
    {
      get { return _c2s_scope; }
      set { _c2s_scope = value; }
    }
    
    private int _c2s_index;
    /// <summary>
    /// 消息index
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"c2s_index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int c2s_index
    {
      get { return _c2s_index; }
      set { _c2s_index = value; }
    }
    
    private string _c2s_uid = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"c2s_uid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string c2s_uid
    {
      get { return _c2s_uid; }
      set { _c2s_uid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OnChatPush")]
  public partial class OnChatPush : global::ProtoBuf.IExtensible
  {
    public OnChatPush() {}
    
    
    private string _s2c_playerId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"s2c_playerId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string s2c_playerId
    {
      get { return _s2c_playerId; }
      set { _s2c_playerId = value; }
    }
    
    private string _s2c_uid;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"s2c_uid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string s2c_uid
    {
      get { return _s2c_uid; }
      set { _s2c_uid = value; }
    }
    
    private string _s2c_content;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"s2c_content", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string s2c_content
    {
      get { return _s2c_content; }
      set { _s2c_content = value; }
    }
    
    private int _s2c_scope;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"s2c_scope", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int s2c_scope
    {
      get { return _s2c_scope; }
      set { _s2c_scope = value; }
    }
    
    private string _s2c_time = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"s2c_time", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string s2c_time
    {
      get { return _s2c_time; }
      set { _s2c_time = value; }
    }
    
    private int _s2c_sys = default(int);
    /// <summary>
    /// 消息的种类 1-系统 2-喇叭
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"s2c_sys", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int s2c_sys
    {
      get { return _s2c_sys; }
      set { _s2c_sys = value; }
    }
    
    private int _s2c_index = default(int);
    /// <summary>
    /// 标志这一条消息
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"s2c_index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int s2c_index
    {
      get { return _s2c_index; }
      set { _s2c_index = value; }
    }
    
    private string _s2c_serverData = "";
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"s2c_serverData", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string s2c_serverData
    {
      get { return _s2c_serverData; }
      set { _s2c_serverData = value; }
    }
    
    private string _s2c_acceptRid = "";
    /// <summary>
    /// (私聊) 接受者id
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"s2c_acceptRid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string s2c_acceptRid
    {
      get { return _s2c_acceptRid; }
      set { _s2c_acceptRid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetSaveChatMsgResponse")]
  public partial class GetSaveChatMsgResponse : global::ProtoBuf.IExtensible
  {
    public GetSaveChatMsgResponse() {}
    
    
    private int _s2c_code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"s2c_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int s2c_code
    {
      get { return _s2c_code; }
      set { _s2c_code = value; }
    }
    
    private string _s2c_msg = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"s2c_msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string s2c_msg
    {
      get { return _s2c_msg; }
      set { _s2c_msg = value; }
    }
    
    private readonly global::System.Collections.Generic.List<pomelo.chat.OnChatPush> _s2c_data = new global::System.Collections.Generic.List<pomelo.chat.OnChatPush>();
    [global::ProtoBuf.ProtoMember(3, Name=@"s2c_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pomelo.chat.OnChatPush> s2c_data
    {
      get { return _s2c_data; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OnChatErrorPush")]
  public partial class OnChatErrorPush : global::ProtoBuf.IExtensible
  {
    public OnChatErrorPush() {}
    
    
    private int _s2c_code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"s2c_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int s2c_code
    {
      get { return _s2c_code; }
      set { _s2c_code = value; }
    }
    
    private string _s2c_msg;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"s2c_msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string s2c_msg
    {
      get { return _s2c_msg; }
      set { _s2c_msg = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  /// <summary>
  /// 提示信息
  /// </summary>
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TipPush")]
  public partial class TipPush : global::ProtoBuf.IExtensible
  {
    public TipPush() {}
    
    
    private string _s2c_msg;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"s2c_msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string s2c_msg
    {
      get { return _s2c_msg; }
      set { _s2c_msg = value; }
    }
    
    private int _s2c_type;
    /// <summary>
    /// 0 普通飘字, 1 新增的飘字
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"s2c_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int s2c_type
    {
      get { return _s2c_type; }
      set { _s2c_type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
}
  