//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// ***************************************************************************
// * 作者= wht
// * 创建时间= 2017-04-10
// * 用途= 道友数据
// ***************************************************************************/

// Generated from: daoYouHandler.proto
namespace pomelo.daoyou
{
  
  //---------------------------------------------------------------------------------------
  /// <summary>
  /// 道友信息
  /// </summary>
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DaoYouInfo")]
  public partial class DaoYouInfo : global::ProtoBuf.IExtensible
  {
    public DaoYouInfo() {}
    
    
    private string _playerId = "";
    /// <summary>
    /// 玩家ID
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    
    private string _playerName = "";
    /// <summary>
    /// 玩家名称
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"playerName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string playerName
    {
      get { return _playerName; }
      set { _playerName = value; }
    }
    
    private int _playerLvl = default(int);
    /// <summary>
    /// 玩家等级
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"playerLvl", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int playerLvl
    {
      get { return _playerLvl; }
      set { _playerLvl = value; }
    }
    
    private int _pro = default(int);
    /// <summary>
    /// 职业
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"pro", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int pro
    {
      get { return _pro; }
      set { _pro = value; }
    }
    
    private int _playerUpLvl = default(int);
    /// <summary>
    /// 玩家进阶等级
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"playerUpLvl", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int playerUpLvl
    {
      get { return _playerUpLvl; }
      set { _playerUpLvl = value; }
    }
    
    private string _areaName = "";
    /// <summary>
    /// 玩家所在场景
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"areaName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string areaName
    {
      get { return _areaName; }
      set { _areaName = value; }
    }
    
    private int _playerFightPower = default(int);
    /// <summary>
    /// 玩家战斗力
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"playerFightPower", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int playerFightPower
    {
      get { return _playerFightPower; }
      set { _playerFightPower = value; }
    }
    
    private int _isAdmin = default(int);
    /// <summary>
    /// 是否是管理员
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"isAdmin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int isAdmin
    {
      get { return _isAdmin; }
      set { _isAdmin = value; }
    }
    
    private int _onlineState = default(int);
    /// <summary>
    /// 在线状态 0: 离线    1:在线
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"onlineState", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int onlineState
    {
      get { return _onlineState; }
      set { _onlineState = value; }
    }
    
    private int _lastActiveTime = default(int);
    /// <summary>
    /// 上次离线时间
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"lastActiveTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int lastActiveTime
    {
      get { return _lastActiveTime; }
      set { _lastActiveTime = value; }
    }
    
    private int _joinTime = default(int);
    /// <summary>
    /// 加入道友的时间
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"joinTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int joinTime
    {
      get { return _joinTime; }
      set { _joinTime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  /// <summary>
  /// 系统和留言信息
  /// </summary>
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DaoYouMessage")]
  public partial class DaoYouMessage : global::ProtoBuf.IExtensible
  {
    public DaoYouMessage() {}
    
    
    private int _type = default(int);
    /// <summary>
    /// 信息类型:1、系统2、留言
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    
    private string _content = "";
    /// <summary>
    /// 内容
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"content", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string content
    {
      get { return _content; }
      set { _content = value; }
    }
    
    private int _time = default(int);
    /// <summary>
    /// 时间
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int time
    {
      get { return _time; }
      set { _time = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  /// <summary>
  /// 打开道友界面请求
  /// </summary>
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DaoYouRequest")]
  public partial class DaoYouRequest : global::ProtoBuf.IExtensible
  {
    public DaoYouRequest() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  /// <summary>
  /// 打开道友界面响应
  /// </summary>
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DaoYouResponse")]
  public partial class DaoYouResponse : global::ProtoBuf.IExtensible
  {
    public DaoYouResponse() {}
    
    
    private int _s2c_code;
    /// <summary>
    /// 状态(1成功、0失败)
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"s2c_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int s2c_code
    {
      get { return _s2c_code; }
      set { _s2c_code = value; }
    }
    
    private string _s2c_msg = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"s2c_msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string s2c_msg
    {
      get { return _s2c_msg; }
      set { _s2c_msg = value; }
    }
    
    private int _isHasDaoYou = default(int);
    /// <summary>
    /// 是否有道友(1有、0没有)
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"isHasDaoYou", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int isHasDaoYou
    {
      get { return _isHasDaoYou; }
      set { _isHasDaoYou = value; }
    }
    
    private int _isEditedDyName = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"isEditedDyName", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int isEditedDyName
    {
      get { return _isEditedDyName; }
      set { _isEditedDyName = value; }
    }
    
    private string _dyId = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"dyId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string dyId
    {
      get { return _dyId; }
      set { _dyId = value; }
    }
    
    private string _dyName = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"dyName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string dyName
    {
      get { return _dyName; }
      set { _dyName = value; }
    }
    
    private int _dyFightPower = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"dyFightPower", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int dyFightPower
    {
      get { return _dyFightPower; }
      set { _dyFightPower = value; }
    }
    
    private int _dyRank = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"dyRank", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int dyRank
    {
      get { return _dyRank; }
      set { _dyRank = value; }
    }
    
    private string _dyNotice = "";
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"dyNotice", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string dyNotice
    {
      get { return _dyNotice; }
      set { _dyNotice = value; }
    }
    
    private readonly global::System.Collections.Generic.List<pomelo.daoyou.DaoYouMessage> _message = new global::System.Collections.Generic.List<pomelo.daoyou.DaoYouMessage>();
    [global::ProtoBuf.ProtoMember(10, Name=@"message", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pomelo.daoyou.DaoYouMessage> message
    {
      get { return _message; }
    }
  
    
    private readonly global::System.Collections.Generic.List<pomelo.daoyou.DaoYouInfo> _dyInfo = new global::System.Collections.Generic.List<pomelo.daoyou.DaoYouInfo>();
    [global::ProtoBuf.ProtoMember(11, Name=@"dyInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pomelo.daoyou.DaoYouInfo> dyInfo
    {
      get { return _dyInfo; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  /// <summary>
  /// 邀请道友请求
  /// </summary>
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DaoYouInviteDaoYouRequest")]
  public partial class DaoYouInviteDaoYouRequest : global::ProtoBuf.IExtensible
  {
    public DaoYouInviteDaoYouRequest() {}
    
    
    private string _playerId;
    /// <summary>
    /// 被邀请的玩家ID
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  /// <summary>
  /// 邀请道友响应
  /// </summary>
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DaoYouInviteDaoYouResponse")]
  public partial class DaoYouInviteDaoYouResponse : global::ProtoBuf.IExtensible
  {
    public DaoYouInviteDaoYouResponse() {}
    
    
    private int _s2c_code;
    /// <summary>
    /// 状态(成功、失败)
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"s2c_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int s2c_code
    {
      get { return _s2c_code; }
      set { _s2c_code = value; }
    }
    
    private string _s2c_msg = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"s2c_msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string s2c_msg
    {
      get { return _s2c_msg; }
      set { _s2c_msg = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  /// <summary>
  /// 快捷组队道友请求
  /// </summary>
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DaoYouFastInviteDaoYouRequest")]
  public partial class DaoYouFastInviteDaoYouRequest : global::ProtoBuf.IExtensible
  {
    public DaoYouFastInviteDaoYouRequest() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  /// <summary>
  /// 快捷组队道友响应
  /// </summary>
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DaoYouFastInviteDaoYouResponse")]
  public partial class DaoYouFastInviteDaoYouResponse : global::ProtoBuf.IExtensible
  {
    public DaoYouFastInviteDaoYouResponse() {}
    
    
    private int _s2c_code;
    /// <summary>
    /// 状态(成功、失败)
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"s2c_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int s2c_code
    {
      get { return _s2c_code; }
      set { _s2c_code = value; }
    }
    
    private string _s2c_msg = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"s2c_msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string s2c_msg
    {
      get { return _s2c_msg; }
      set { _s2c_msg = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  /// <summary>
  /// 修改道友名称请求
  /// </summary>
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DaoYouEditTeamNameRequest")]
  public partial class DaoYouEditTeamNameRequest : global::ProtoBuf.IExtensible
  {
    public DaoYouEditTeamNameRequest() {}
    
    
    private string _teamName;
    /// <summary>
    /// 道友团队名称
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"teamName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string teamName
    {
      get { return _teamName; }
      set { _teamName = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  /// <summary>
  /// 修改道友名称响应
  /// </summary>
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DaoYouEditTeamNameResponse")]
  public partial class DaoYouEditTeamNameResponse : global::ProtoBuf.IExtensible
  {
    public DaoYouEditTeamNameResponse() {}
    
    
    private int _s2c_code;
    /// <summary>
    /// 状态(成功、失败)
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"s2c_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int s2c_code
    {
      get { return _s2c_code; }
      set { _s2c_code = value; }
    }
    
    private string _s2c_msg = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"s2c_msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string s2c_msg
    {
      get { return _s2c_msg; }
      set { _s2c_msg = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  /// <summary>
  /// 留言请求
  /// </summary>
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DaoYouLeaveMessageRequest")]
  public partial class DaoYouLeaveMessageRequest : global::ProtoBuf.IExtensible
  {
    public DaoYouLeaveMessageRequest() {}
    
    
    private string _message;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"message", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string message
    {
      get { return _message; }
      set { _message = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  /// <summary>
  /// 留言响应
  /// </summary>
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DaoYouLeaveMessageResponse")]
  public partial class DaoYouLeaveMessageResponse : global::ProtoBuf.IExtensible
  {
    public DaoYouLeaveMessageResponse() {}
    
    
    private int _s2c_code;
    /// <summary>
    /// 状态(成功、失败)
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"s2c_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int s2c_code
    {
      get { return _s2c_code; }
      set { _s2c_code = value; }
    }
    
    private string _s2c_msg = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"s2c_msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string s2c_msg
    {
      get { return _s2c_msg; }
      set { _s2c_msg = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  /// <summary>
  /// 公告请求
  /// </summary>
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DaoYouNoticeRequest")]
  public partial class DaoYouNoticeRequest : global::ProtoBuf.IExtensible
  {
    public DaoYouNoticeRequest() {}
    
    
    private string _notice;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"notice", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string notice
    {
      get { return _notice; }
      set { _notice = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  /// <summary>
  /// 公告响应
  /// </summary>
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DaoYouNoticeResponse")]
  public partial class DaoYouNoticeResponse : global::ProtoBuf.IExtensible
  {
    public DaoYouNoticeResponse() {}
    
    
    private int _s2c_code;
    /// <summary>
    /// 状态(成功、失败)
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"s2c_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int s2c_code
    {
      get { return _s2c_code; }
      set { _s2c_code = value; }
    }
    
    private string _s2c_msg = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"s2c_msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string s2c_msg
    {
      get { return _s2c_msg; }
      set { _s2c_msg = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  /// <summary>
  /// 踢出道友团队请求
  /// </summary>
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DaoYouKickTeamRequest")]
  public partial class DaoYouKickTeamRequest : global::ProtoBuf.IExtensible
  {
    public DaoYouKickTeamRequest() {}
    
    
    private string _playerId;
    /// <summary>
    /// 被踢的玩家ID
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  /// <summary>
  /// 踢出道友团队响应
  /// </summary>
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DaoYouKickTeamResponse")]
  public partial class DaoYouKickTeamResponse : global::ProtoBuf.IExtensible
  {
    public DaoYouKickTeamResponse() {}
    
    
    private int _s2c_code;
    /// <summary>
    /// 状态(成功、失败)
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"s2c_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int s2c_code
    {
      get { return _s2c_code; }
      set { _s2c_code = value; }
    }
    
    private string _s2c_msg = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"s2c_msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string s2c_msg
    {
      get { return _s2c_msg; }
      set { _s2c_msg = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  /// <summary>
  /// 转让管理职位请求
  /// </summary>
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DaoYouTransferAdminRequest")]
  public partial class DaoYouTransferAdminRequest : global::ProtoBuf.IExtensible
  {
    public DaoYouTransferAdminRequest() {}
    
    
    private string _playerId;
    /// <summary>
    /// 转让的玩家ID
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  /// <summary>
  /// 转让管理职位响应
  /// </summary>
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DaoYouTransferAdminResponse")]
  public partial class DaoYouTransferAdminResponse : global::ProtoBuf.IExtensible
  {
    public DaoYouTransferAdminResponse() {}
    
    
    private int _s2c_code;
    /// <summary>
    /// 状态(成功、失败)
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"s2c_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int s2c_code
    {
      get { return _s2c_code; }
      set { _s2c_code = value; }
    }
    
    private string _s2c_msg = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"s2c_msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string s2c_msg
    {
      get { return _s2c_msg; }
      set { _s2c_msg = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  /// <summary>
  /// 退出道友请求
  /// </summary>
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DaoYouQuitTeamRequest")]
  public partial class DaoYouQuitTeamRequest : global::ProtoBuf.IExtensible
  {
    public DaoYouQuitTeamRequest() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  /// <summary>
  /// 退出道友响应
  /// </summary>
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DaoYouQuitTeamResponse")]
  public partial class DaoYouQuitTeamResponse : global::ProtoBuf.IExtensible
  {
    public DaoYouQuitTeamResponse() {}
    
    
    private int _s2c_code;
    /// <summary>
    /// 状态(成功、失败)
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"s2c_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int s2c_code
    {
      get { return _s2c_code; }
      set { _s2c_code = value; }
    }
    
    private string _s2c_msg = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"s2c_msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string s2c_msg
    {
      get { return _s2c_msg; }
      set { _s2c_msg = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  /// <summary>
  /// 道友返利请求
  /// </summary>
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DaoYouRebateRequest")]
  public partial class DaoYouRebateRequest : global::ProtoBuf.IExtensible
  {
    public DaoYouRebateRequest() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  /// <summary>
  /// 道友成员收到返利信息
  /// </summary>
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DaoYouMemRebaeReciveInfo")]
  public partial class DaoYouMemRebaeReciveInfo : global::ProtoBuf.IExtensible
  {
    public DaoYouMemRebaeReciveInfo() {}
    
    
    private string _playerName = "";
    /// <summary>
    /// 玩家名称
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"playerName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string playerName
    {
      get { return _playerName; }
      set { _playerName = value; }
    }
    
    private int _reciveNumber = default(int);
    /// <summary>
    /// 获得数量
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"reciveNumber", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int reciveNumber
    {
      get { return _reciveNumber; }
      set { _reciveNumber = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  /// <summary>
  /// 返利信息
  /// </summary>
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DaoYouRebateInfo")]
  public partial class DaoYouRebateInfo : global::ProtoBuf.IExtensible
  {
    public DaoYouRebateInfo() {}
    
    
    private string _playerName = "";
    /// <summary>
    /// 玩家名称
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"playerName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string playerName
    {
      get { return _playerName; }
      set { _playerName = value; }
    }
    
    private int _totalSendRebate = default(int);
    /// <summary>
    /// 累计发放
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"totalSendRebate", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int totalSendRebate
    {
      get { return _totalSendRebate; }
      set { _totalSendRebate = value; }
    }
    
    private int _todaySendRebate = default(int);
    /// <summary>
    /// 今日发放
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"todaySendRebate", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int todaySendRebate
    {
      get { return _todaySendRebate; }
      set { _todaySendRebate = value; }
    }
    
    private readonly global::System.Collections.Generic.List<pomelo.daoyou.DaoYouMemRebaeReciveInfo> _memRebaeReciveInfo = new global::System.Collections.Generic.List<pomelo.daoyou.DaoYouMemRebaeReciveInfo>();
    /// <summary>
    /// 道友成员收到返利信息
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(4, Name=@"memRebaeReciveInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pomelo.daoyou.DaoYouMemRebaeReciveInfo> memRebaeReciveInfo
    {
      get { return _memRebaeReciveInfo; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  /// <summary>
  /// 道友返利响应
  /// </summary>
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DaoYouRebateResponse")]
  public partial class DaoYouRebateResponse : global::ProtoBuf.IExtensible
  {
    public DaoYouRebateResponse() {}
    
    
    private int _s2c_code;
    /// <summary>
    /// 状态(成功、失败)
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"s2c_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int s2c_code
    {
      get { return _s2c_code; }
      set { _s2c_code = value; }
    }
    
    private string _s2c_msg = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"s2c_msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string s2c_msg
    {
      get { return _s2c_msg; }
      set { _s2c_msg = value; }
    }
    
    private int _selfTotalReciveRebate = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"selfTotalReciveRebate", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int selfTotalReciveRebate
    {
      get { return _selfTotalReciveRebate; }
      set { _selfTotalReciveRebate = value; }
    }
    
    private int _selfTodayReciveRebate = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"selfTodayReciveRebate", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int selfTodayReciveRebate
    {
      get { return _selfTodayReciveRebate; }
      set { _selfTodayReciveRebate = value; }
    }
    
    private readonly global::System.Collections.Generic.List<pomelo.daoyou.DaoYouRebateInfo> _ri = new global::System.Collections.Generic.List<pomelo.daoyou.DaoYouRebateInfo>();
    [global::ProtoBuf.ProtoMember(5, Name=@"ri", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pomelo.daoyou.DaoYouRebateInfo> ri
    {
      get { return _ri; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
}
  