//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// ***************************************************************************
// * 作者= wht
// * 创建时间= 2017-04-15
// * 用途= 5v5数据
// ***************************************************************************/

// Generated from: five2FiveHandler.proto
// Note: requires additional types generated from: common.proto
namespace pomelo.five2five
{
  
  //---------------------------------------------------------------------------------------
  /// <summary>
  /// 打开5v5界面请求
  /// </summary>
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Five2FiveRequest")]
  public partial class Five2FiveRequest : global::ProtoBuf.IExtensible
  {
    public Five2FiveRequest() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  /// <summary>
  /// 5v5排行信息
  /// </summary>
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Five2FiveRankInfo")]
  public partial class Five2FiveRankInfo : global::ProtoBuf.IExtensible
  {
    public Five2FiveRankInfo() {}
    
    
    private string _playerId = "";
    /// <summary>
    /// 玩家ID
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    
    private string _playerName = "";
    /// <summary>
    /// 玩家名称
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"playerName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string playerName
    {
      get { return _playerName; }
      set { _playerName = value; }
    }
    
    private int _playerLvl = default(int);
    /// <summary>
    /// 玩家等级
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"playerLvl", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int playerLvl
    {
      get { return _playerLvl; }
      set { _playerLvl = value; }
    }
    
    private int _pro = default(int);
    /// <summary>
    /// 职业
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"pro", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int pro
    {
      get { return _pro; }
      set { _pro = value; }
    }
    
    private int _playerUpLvl = default(int);
    /// <summary>
    /// 玩家进阶等级
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"playerUpLvl", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int playerUpLvl
    {
      get { return _playerUpLvl; }
      set { _playerUpLvl = value; }
    }
    
    private int _playerFightPower = default(int);
    /// <summary>
    /// 玩家战斗力
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"playerFightPower", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int playerFightPower
    {
      get { return _playerFightPower; }
      set { _playerFightPower = value; }
    }
    
    private int _score = default(int);
    /// <summary>
    /// 积分
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"score", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int score
    {
      get { return _score; }
      set { _score = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  /// <summary>
  /// 5v5匹配时间
  /// </summary>
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Five2FiveMatchTime")]
  public partial class Five2FiveMatchTime : global::ProtoBuf.IExtensible
  {
    public Five2FiveMatchTime() {}
    
    
    private int _avgWaitTime = default(int);
    /// <summary>
    /// 平均等待时间(若没有匹配则该值与后面值为0)
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"avgWaitTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int avgWaitTime
    {
      get { return _avgWaitTime; }
      set { _avgWaitTime = value; }
    }
    
    private int _matchTime = default(int);
    /// <summary>
    /// 开始匹配的时间
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"matchTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int matchTime
    {
      get { return _matchTime; }
      set { _matchTime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  /// <summary>
  /// 打开5v5界面响应
  /// </summary>
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Five2FiveResponse")]
  public partial class Five2FiveResponse : global::ProtoBuf.IExtensible
  {
    public Five2FiveResponse() {}
    
    
    private int _s2c_code;
    /// <summary>
    /// 状态(1成功、0失败)
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"s2c_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int s2c_code
    {
      get { return _s2c_code; }
      set { _s2c_code = value; }
    }
    
    private string _s2c_msg = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"s2c_msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string s2c_msg
    {
      get { return _s2c_msg; }
      set { _s2c_msg = value; }
    }
    
    private pomelo.five2five.Five2FiveRankInfo _firstRankInfo = null;
    /// <summary>
    /// 排名第一的玩家信息
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"firstRankInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public pomelo.five2five.Five2FiveRankInfo firstRankInfo
    {
      get { return _firstRankInfo; }
      set { _firstRankInfo = value; }
    }
    
    private int _score = default(int);
    /// <summary>
    /// 积分
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"score", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int score
    {
      get { return _score; }
      set { _score = value; }
    }
    
    private int _rank = default(int);
    /// <summary>
    /// 排名
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"rank", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int rank
    {
      get { return _rank; }
      set { _rank = value; }
    }
    
    private int _win = default(int);
    /// <summary>
    /// 胜利场数
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"win", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int win
    {
      get { return _win; }
      set { _win = value; }
    }
    
    private int _tie = default(int);
    /// <summary>
    /// 平局场数
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"tie", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int tie
    {
      get { return _tie; }
      set { _tie = value; }
    }
    
    private int _fail = default(int);
    /// <summary>
    /// 失败场数
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"fail", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int fail
    {
      get { return _fail; }
      set { _fail = value; }
    }
    
    private int _mvp = default(int);
    /// <summary>
    /// mvp次数
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"mvp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int mvp
    {
      get { return _mvp; }
      set { _mvp = value; }
    }
    
    private int _totalCanReciveCount = default(int);
    /// <summary>
    /// 当天战斗的次数
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"totalCanReciveCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int totalCanReciveCount
    {
      get { return _totalCanReciveCount; }
      set { _totalCanReciveCount = value; }
    }
    
    private int _hasRecivedCount = default(int);
    /// <summary>
    /// 已经领取奖励的次数
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"hasRecivedCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int hasRecivedCount
    {
      get { return _hasRecivedCount; }
      set { _hasRecivedCount = value; }
    }
    
    private pomelo.five2five.Five2FiveMatchTime _five2FiveMatchTime = null;
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"five2FiveMatchTime", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public pomelo.five2five.Five2FiveMatchTime five2FiveMatchTime
    {
      get { return _five2FiveMatchTime; }
      set { _five2FiveMatchTime = value; }
    }
    
    private int _matchPeople = default(int);
    /// <summary>
    /// 正在匹配的人数
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"matchPeople", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int matchPeople
    {
      get { return _matchPeople; }
      set { _matchPeople = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  /// <summary>
  /// 查看战报请求
  /// </summary>
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Five2FiveLookBtlReportRequest")]
  public partial class Five2FiveLookBtlReportRequest : global::ProtoBuf.IExtensible
  {
    public Five2FiveLookBtlReportRequest() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  /// <summary>
  /// 战报信息
  /// </summary>
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Five2FiveBtlReport")]
  public partial class Five2FiveBtlReport : global::ProtoBuf.IExtensible
  {
    public Five2FiveBtlReport() {}
    
    
    private int _status = default(int);
    /// <summary>
    /// 状态(1-胜 2-负 3-平)
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int status
    {
      get { return _status; }
      set { _status = value; }
    }
    
    private int _scoreChange = default(int);
    /// <summary>
    /// 积分变化
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"scoreChange", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int scoreChange
    {
      get { return _scoreChange; }
      set { _scoreChange = value; }
    }
    
    private int _killCount = default(int);
    /// <summary>
    /// 击杀个数
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"killCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int killCount
    {
      get { return _killCount; }
      set { _killCount = value; }
    }
    
    private int _hurt = default(int);
    /// <summary>
    /// 伤害
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"hurt", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int hurt
    {
      get { return _hurt; }
      set { _hurt = value; }
    }
    
    private int _treatMent = default(int);
    /// <summary>
    /// 治疗
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"treatMent", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int treatMent
    {
      get { return _treatMent; }
      set { _treatMent = value; }
    }
    
    private string _createTime = "";
    /// <summary>
    /// 创建时间(YYYY/MM/dd)
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"createTime", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string createTime
    {
      get { return _createTime; }
      set { _createTime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  /// <summary>
  /// 查看战报响应
  /// </summary>
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Five2FiveLookBtlReportResponse")]
  public partial class Five2FiveLookBtlReportResponse : global::ProtoBuf.IExtensible
  {
    public Five2FiveLookBtlReportResponse() {}
    
    
    private int _s2c_code;
    /// <summary>
    /// 状态(1成功、0失败)
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"s2c_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int s2c_code
    {
      get { return _s2c_code; }
      set { _s2c_code = value; }
    }
    
    private string _s2c_msg = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"s2c_msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string s2c_msg
    {
      get { return _s2c_msg; }
      set { _s2c_msg = value; }
    }
    
    private readonly global::System.Collections.Generic.List<pomelo.five2five.Five2FiveBtlReport> _br = new global::System.Collections.Generic.List<pomelo.five2five.Five2FiveBtlReport>();
    /// <summary>
    /// 战报
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(3, Name=@"br", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pomelo.five2five.Five2FiveBtlReport> br
    {
      get { return _br; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  /// <summary>
  /// 请求匹配
  /// </summary>
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Five2FiveMatchRequest")]
  public partial class Five2FiveMatchRequest : global::ProtoBuf.IExtensible
  {
    public Five2FiveMatchRequest() {}
    
    
    private int _matchOrReMatch;
    /// <summary>
    /// 匹配或者重新匹配(1匹配2重新匹配)
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"matchOrReMatch", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int matchOrReMatch
    {
      get { return _matchOrReMatch; }
      set { _matchOrReMatch = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  /// <summary>
  /// 匹配返回
  /// </summary>
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Five2FiveMatchResponse")]
  public partial class Five2FiveMatchResponse : global::ProtoBuf.IExtensible
  {
    public Five2FiveMatchResponse() {}
    
    
    private int _s2c_code;
    /// <summary>
    /// 状态(1成功、0失败)
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"s2c_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int s2c_code
    {
      get { return _s2c_code; }
      set { _s2c_code = value; }
    }
    
    private string _s2c_msg = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"s2c_msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string s2c_msg
    {
      get { return _s2c_msg; }
      set { _s2c_msg = value; }
    }
    
    private pomelo.five2five.Five2FiveMatchTime _five2FiveMatchTime = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"five2FiveMatchTime", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public pomelo.five2five.Five2FiveMatchTime five2FiveMatchTime
    {
      get { return _five2FiveMatchTime; }
      set { _five2FiveMatchTime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  /// <summary>
  /// 拒绝5v5匹配
  /// </summary>
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Five2FiveRefuseMatchRequest")]
  public partial class Five2FiveRefuseMatchRequest : global::ProtoBuf.IExtensible
  {
    public Five2FiveRefuseMatchRequest() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  /// <summary>
  /// 拒绝5v5匹配响应
  /// </summary>
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Five2FiveRefuseMatchResponse")]
  public partial class Five2FiveRefuseMatchResponse : global::ProtoBuf.IExtensible
  {
    public Five2FiveRefuseMatchResponse() {}
    
    
    private int _s2c_code;
    /// <summary>
    /// 状态(1成功、0失败)
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"s2c_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int s2c_code
    {
      get { return _s2c_code; }
      set { _s2c_code = value; }
    }
    
    private string _s2c_msg = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"s2c_msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string s2c_msg
    {
      get { return _s2c_msg; }
      set { _s2c_msg = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  /// <summary>
  /// 同意5v5匹配
  /// </summary>
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Five2FiveAgreeMatchRequest")]
  public partial class Five2FiveAgreeMatchRequest : global::ProtoBuf.IExtensible
  {
    public Five2FiveAgreeMatchRequest() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  /// <summary>
  /// 同意5v5响应
  /// </summary>
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Five2FiveAgreeMatchResponse")]
  public partial class Five2FiveAgreeMatchResponse : global::ProtoBuf.IExtensible
  {
    public Five2FiveAgreeMatchResponse() {}
    
    
    private int _s2c_code;
    /// <summary>
    /// 状态(1成功、0失败)
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"s2c_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int s2c_code
    {
      get { return _s2c_code; }
      set { _s2c_code = value; }
    }
    
    private string _s2c_msg = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"s2c_msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string s2c_msg
    {
      get { return _s2c_msg; }
      set { _s2c_msg = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  /// <summary>
  /// 取消匹配
  /// </summary>
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Five2FiveCancelMatchRequest")]
  public partial class Five2FiveCancelMatchRequest : global::ProtoBuf.IExtensible
  {
    public Five2FiveCancelMatchRequest() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  /// <summary>
  /// 取消匹配响应
  /// </summary>
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Five2FiveCancelMatchResponse")]
  public partial class Five2FiveCancelMatchResponse : global::ProtoBuf.IExtensible
  {
    public Five2FiveCancelMatchResponse() {}
    
    
    private int _s2c_code;
    /// <summary>
    /// 状态(1成功、0失败)
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"s2c_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int s2c_code
    {
      get { return _s2c_code; }
      set { _s2c_code = value; }
    }
    
    private string _s2c_msg = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"s2c_msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string s2c_msg
    {
      get { return _s2c_msg; }
      set { _s2c_msg = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  /// <summary>
  /// 准备就绪
  /// </summary>
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Five2FiveReadyRequest")]
  public partial class Five2FiveReadyRequest : global::ProtoBuf.IExtensible
  {
    public Five2FiveReadyRequest() {}
    
    
    private string _tempTeamId;
    /// <summary>
    /// 临时组队的ID
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"tempTeamId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string tempTeamId
    {
      get { return _tempTeamId; }
      set { _tempTeamId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  /// <summary>
  /// 准备就绪响应
  /// </summary>
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Five2FiveReadyResponse")]
  public partial class Five2FiveReadyResponse : global::ProtoBuf.IExtensible
  {
    public Five2FiveReadyResponse() {}
    
    
    private int _s2c_code;
    /// <summary>
    /// 状态(1成功、0失败)
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"s2c_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int s2c_code
    {
      get { return _s2c_code; }
      set { _s2c_code = value; }
    }
    
    private string _s2c_msg = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"s2c_msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string s2c_msg
    {
      get { return _s2c_msg; }
      set { _s2c_msg = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  /// <summary>
  /// 领取奖励请求
  /// </summary>
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Five2FiveReciveRewardRequest")]
  public partial class Five2FiveReciveRewardRequest : global::ProtoBuf.IExtensible
  {
    public Five2FiveReciveRewardRequest() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  /// <summary>
  /// 领取奖励响应
  /// </summary>
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Five2FiveReciveRewardResponse")]
  public partial class Five2FiveReciveRewardResponse : global::ProtoBuf.IExtensible
  {
    public Five2FiveReciveRewardResponse() {}
    
    
    private int _s2c_code;
    /// <summary>
    /// 状态(1成功、0失败)
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"s2c_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int s2c_code
    {
      get { return _s2c_code; }
      set { _s2c_code = value; }
    }
    
    private string _s2c_msg = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"s2c_msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string s2c_msg
    {
      get { return _s2c_msg; }
      set { _s2c_msg = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  /// <summary>
  /// 离开场景
  /// </summary>
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Five2FiveLeaveAreaRequest")]
  public partial class Five2FiveLeaveAreaRequest : global::ProtoBuf.IExtensible
  {
    public Five2FiveLeaveAreaRequest() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  /// <summary>
  /// 离开场景响应
  /// </summary>
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Five2FiveLeaveAreaResponse")]
  public partial class Five2FiveLeaveAreaResponse : global::ProtoBuf.IExtensible
  {
    public Five2FiveLeaveAreaResponse() {}
    
    
    private int _s2c_code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"s2c_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int s2c_code
    {
      get { return _s2c_code; }
      set { _s2c_code = value; }
    }
    
    private string _s2c_msg = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"s2c_msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string s2c_msg
    {
      get { return _s2c_msg; }
      set { _s2c_msg = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  /// <summary>
  /// 每个人的战斗信息
  /// </summary>
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Five2FivePlayerResultInfo")]
  public partial class Five2FivePlayerResultInfo : global::ProtoBuf.IExtensible
  {
    public Five2FivePlayerResultInfo() {}
    
    
    private string _playerId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    
    private int _killCount;
    /// <summary>
    /// 击杀个数
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"killCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int killCount
    {
      get { return _killCount; }
      set { _killCount = value; }
    }
    
    private int _hurt;
    /// <summary>
    /// 伤害
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"hurt", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int hurt
    {
      get { return _hurt; }
      set { _hurt = value; }
    }
    
    private int _treatMent;
    /// <summary>
    /// 治疗
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"treatMent", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int treatMent
    {
      get { return _treatMent; }
      set { _treatMent = value; }
    }
    
    private int _isMvp;
    /// <summary>
    /// 是否MVP
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"isMvp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int isMvp
    {
      get { return _isMvp; }
      set { _isMvp = value; }
    }
    
    private string _playerName;
    /// <summary>
    /// 玩家名字
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"playerName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string playerName
    {
      get { return _playerName; }
      set { _playerName = value; }
    }
    
    private int _playerLevel;
    /// <summary>
    /// 玩家等级
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"playerLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int playerLevel
    {
      get { return _playerLevel; }
      set { _playerLevel = value; }
    }
    
    private int _playerPro;
    /// <summary>
    /// 玩家职业
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"playerPro", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int playerPro
    {
      get { return _playerPro; }
      set { _playerPro = value; }
    }
    
    private int _deadCount;
    /// <summary>
    /// 死亡次数
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"deadCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int deadCount
    {
      get { return _deadCount; }
      set { _deadCount = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  /// <summary>
  /// 请求查看比赛结果
  /// </summary>
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Five2FiveLookMatchResultRequest")]
  public partial class Five2FiveLookMatchResultRequest : global::ProtoBuf.IExtensible
  {
    public Five2FiveLookMatchResultRequest() {}
    
    
    private string _instanceId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"instanceId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string instanceId
    {
      get { return _instanceId; }
      set { _instanceId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  /// <summary>
  /// 查看比赛结果
  /// </summary>
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Five2FiveLookMatchResultResponse")]
  public partial class Five2FiveLookMatchResultResponse : global::ProtoBuf.IExtensible
  {
    public Five2FiveLookMatchResultResponse() {}
    
    
    private int _s2c_code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"s2c_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int s2c_code
    {
      get { return _s2c_code; }
      set { _s2c_code = value; }
    }
    
    private string _s2c_msg = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"s2c_msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string s2c_msg
    {
      get { return _s2c_msg; }
      set { _s2c_msg = value; }
    }
    
    private readonly global::System.Collections.Generic.List<pomelo.five2five.Five2FivePlayerResultInfo> _resultInfoA = new global::System.Collections.Generic.List<pomelo.five2five.Five2FivePlayerResultInfo>();
    [global::ProtoBuf.ProtoMember(3, Name=@"resultInfoA", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pomelo.five2five.Five2FivePlayerResultInfo> resultInfoA
    {
      get { return _resultInfoA; }
    }
  
    
    private readonly global::System.Collections.Generic.List<pomelo.five2five.Five2FivePlayerResultInfo> _resultInfoB = new global::System.Collections.Generic.List<pomelo.five2five.Five2FivePlayerResultInfo>();
    [global::ProtoBuf.ProtoMember(4, Name=@"resultInfoB", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pomelo.five2five.Five2FivePlayerResultInfo> resultInfoB
    {
      get { return _resultInfoB; }
    }
  
    
    private int _resultA = default(int);
    /// <summary>
    /// A队胜负结果(1-胜 2-负 3-平)
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"resultA", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int resultA
    {
      get { return _resultA; }
      set { _resultA = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  /// <summary>
  /// 分享比赛战报
  /// </summary>
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Five2FiveShardMatchResultRequest")]
  public partial class Five2FiveShardMatchResultRequest : global::ProtoBuf.IExtensible
  {
    public Five2FiveShardMatchResultRequest() {}
    
    
    private string _instanceId;
    /// <summary>
    /// 比赛结果唯一ID
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"instanceId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string instanceId
    {
      get { return _instanceId; }
      set { _instanceId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  /// <summary>
  /// 分享比赛战报响应
  /// </summary>
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Five2FiveShardMatchResultResponse")]
  public partial class Five2FiveShardMatchResultResponse : global::ProtoBuf.IExtensible
  {
    public Five2FiveShardMatchResultResponse() {}
    
    
    private int _s2c_code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"s2c_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int s2c_code
    {
      get { return _s2c_code; }
      set { _s2c_code = value; }
    }
    
    private string _s2c_msg = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"s2c_msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string s2c_msg
    {
      get { return _s2c_msg; }
      set { _s2c_msg = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  /// <summary>
  /// 队伍成员变化队长选择(继续队列OR重新匹配)
  /// </summary>
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Five2FiveTeamChangeContinueRequest")]
  public partial class Five2FiveTeamChangeContinueRequest : global::ProtoBuf.IExtensible
  {
    public Five2FiveTeamChangeContinueRequest() {}
    
    
    private int _choice;
    /// <summary>
    /// 1继续队列2重新匹配
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"choice", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int choice
    {
      get { return _choice; }
      set { _choice = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  /// <summary>
  /// 玩家匹配信息
  /// </summary>
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Five2FiveMatchMemberInfo")]
  public partial class Five2FiveMatchMemberInfo : global::ProtoBuf.IExtensible
  {
    public Five2FiveMatchMemberInfo() {}
    
    
    private string _playerId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    
    private int _playerPro;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"playerPro", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int playerPro
    {
      get { return _playerPro; }
      set { _playerPro = value; }
    }
    
    private int _playerLvl;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"playerLvl", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int playerLvl
    {
      get { return _playerLvl; }
      set { _playerLvl = value; }
    }
    
    private string _playerName;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"playerName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string playerName
    {
      get { return _playerName; }
      set { _playerName = value; }
    }
    
    private int _readyStatus;
    /// <summary>
    /// 1拒绝2同意
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"readyStatus", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int readyStatus
    {
      get { return _readyStatus; }
      set { _readyStatus = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  /// <summary>
  /// 推送请求进入5v5
  /// </summary>
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Five2FiveApplyMatchPush")]
  public partial class Five2FiveApplyMatchPush : global::ProtoBuf.IExtensible
  {
    public Five2FiveApplyMatchPush() {}
    
    
    private readonly global::System.Collections.Generic.List<pomelo.five2five.Five2FiveMatchMemberInfo> _five2FiveMatchMemberInfo = new global::System.Collections.Generic.List<pomelo.five2five.Five2FiveMatchMemberInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"five2FiveMatchMemberInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pomelo.five2five.Five2FiveMatchMemberInfo> five2FiveMatchMemberInfo
    {
      get { return _five2FiveMatchMemberInfo; }
    }
  
    
    private int _waitResponseTimeSec;
    /// <summary>
    /// 等待用户回应的时间秒数
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"waitResponseTimeSec", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int waitResponseTimeSec
    {
      get { return _waitResponseTimeSec; }
      set { _waitResponseTimeSec = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  /// <summary>
  /// 推送匹配到的玩家
  /// </summary>
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Five2FiveMatchMemberInfoPush")]
  public partial class Five2FiveMatchMemberInfoPush : global::ProtoBuf.IExtensible
  {
    public Five2FiveMatchMemberInfoPush() {}
    
    
    private int _s2c_code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"s2c_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int s2c_code
    {
      get { return _s2c_code; }
      set { _s2c_code = value; }
    }
    
    private string _tempTeamId;
    /// <summary>
    /// 临时组队的ID
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"tempTeamId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string tempTeamId
    {
      get { return _tempTeamId; }
      set { _tempTeamId = value; }
    }
    
    private readonly global::System.Collections.Generic.List<pomelo.five2five.Five2FiveMatchMemberInfo> _matchTeamInfoA = new global::System.Collections.Generic.List<pomelo.five2five.Five2FiveMatchMemberInfo>();
    /// <summary>
    /// 客户端根据玩家ID判断队友还是对手
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(3, Name=@"matchTeamInfoA", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pomelo.five2five.Five2FiveMatchMemberInfo> matchTeamInfoA
    {
      get { return _matchTeamInfoA; }
    }
  
    
    private readonly global::System.Collections.Generic.List<pomelo.five2five.Five2FiveMatchMemberInfo> _matchTeamInfoB = new global::System.Collections.Generic.List<pomelo.five2five.Five2FiveMatchMemberInfo>();
    /// <summary>
    /// 客户端根据玩家ID判断队友还是对手
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(4, Name=@"matchTeamInfoB", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pomelo.five2five.Five2FiveMatchMemberInfo> matchTeamInfoB
    {
      get { return _matchTeamInfoB; }
    }
  
    
    private int _waitResponseTimeSec;
    /// <summary>
    /// 等待用户回应的时间秒数
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"waitResponseTimeSec", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int waitResponseTimeSec
    {
      get { return _waitResponseTimeSec; }
      set { _waitResponseTimeSec = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  /// <summary>
  /// 推送队友的选择(放弃、准备就绪)
  /// </summary>
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Five2FiveMemberChoicePush")]
  public partial class Five2FiveMemberChoicePush : global::ProtoBuf.IExtensible
  {
    public Five2FiveMemberChoicePush() {}
    
    
    private int _s2c_code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"s2c_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int s2c_code
    {
      get { return _s2c_code; }
      set { _s2c_code = value; }
    }
    
    private int _agreeOrReady;
    /// <summary>
    /// 同意匹配类型或者准备就绪进入1、同意匹配2、准备就绪类型
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"agreeOrReady", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int agreeOrReady
    {
      get { return _agreeOrReady; }
      set { _agreeOrReady = value; }
    }
    
    private string _playerId;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    
    private int _choice;
    /// <summary>
    /// 1放弃、2准备就绪
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"choice", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int choice
    {
      get { return _choice; }
      set { _choice = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  /// <summary>
  /// 战斗结果
  /// </summary>
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Five2FiveGameResult")]
  public partial class Five2FiveGameResult : global::ProtoBuf.IExtensible
  {
    public Five2FiveGameResult() {}
    
    
    private int _result;
    /// <summary>
    /// 1-胜 2-负 3-平
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    
    private int _newScore;
    /// <summary>
    /// 修改 新增积分
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"newScore", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int newScore
    {
      get { return _newScore; }
      set { _newScore = value; }
    }
    
    private int _currScore;
    /// <summary>
    /// 新增 当前积分
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"currScore", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int currScore
    {
      get { return _currScore; }
      set { _currScore = value; }
    }
    
    private int _mvpCount;
    /// <summary>
    /// 修改 mvp次数
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"mvpCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int mvpCount
    {
      get { return _mvpCount; }
      set { _mvpCount = value; }
    }
    
    private int _rankChange;
    /// <summary>
    /// 新增 排名变化
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"rankChange", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int rankChange
    {
      get { return _rankChange; }
      set { _rankChange = value; }
    }
    
    private string _instanceId;
    /// <summary>
    /// 比赛结果唯一ID
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"instanceId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string instanceId
    {
      get { return _instanceId; }
      set { _instanceId = value; }
    }
    
    private int _currRank;
    /// <summary>
    /// 当前排名
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"currRank", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int currRank
    {
      get { return _currRank; }
      set { _currRank = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  /// <summary>
  /// 全场结束
  /// </summary>
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Five2FiveOnGameEndPush")]
  public partial class Five2FiveOnGameEndPush : global::ProtoBuf.IExtensible
  {
    public Five2FiveOnGameEndPush() {}
    
    
    private int _s2c_code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"s2c_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int s2c_code
    {
      get { return _s2c_code; }
      set { _s2c_code = value; }
    }
    
    private pomelo.five2five.Five2FiveGameResult _s2c_gameResult;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"s2c_gameResult", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public pomelo.five2five.Five2FiveGameResult s2c_gameResult
    {
      get { return _s2c_gameResult; }
      set { _s2c_gameResult = value; }
    }
    
    private int _s2c_gameOverTime;
    /// <summary>
    /// 玩家离开场景倒计时
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"s2c_gameOverTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int s2c_gameOverTime
    {
      get { return _s2c_gameOverTime; }
      set { _s2c_gameOverTime = value; }
    }
    
    private readonly global::System.Collections.Generic.List<pomelo.five2five.Five2FivePlayerResultInfo> _resultInfoA = new global::System.Collections.Generic.List<pomelo.five2five.Five2FivePlayerResultInfo>();
    [global::ProtoBuf.ProtoMember(4, Name=@"resultInfoA", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pomelo.five2five.Five2FivePlayerResultInfo> resultInfoA
    {
      get { return _resultInfoA; }
    }
  
    
    private readonly global::System.Collections.Generic.List<pomelo.five2five.Five2FivePlayerResultInfo> _resultInfoB = new global::System.Collections.Generic.List<pomelo.five2five.Five2FivePlayerResultInfo>();
    [global::ProtoBuf.ProtoMember(5, Name=@"resultInfoB", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pomelo.five2five.Five2FivePlayerResultInfo> resultInfoB
    {
      get { return _resultInfoB; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  /// <summary>
  /// 有新奖励
  /// </summary>
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Five2FiveOnNewRewardPush")]
  public partial class Five2FiveOnNewRewardPush : global::ProtoBuf.IExtensible
  {
    public Five2FiveOnNewRewardPush() {}
    
    
    private int _s2c_code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"s2c_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int s2c_code
    {
      get { return _s2c_code; }
      set { _s2c_code = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  /// <summary>
  /// 无可领取奖励
  /// </summary>
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Five2FiveOnNoRewardPush")]
  public partial class Five2FiveOnNoRewardPush : global::ProtoBuf.IExtensible
  {
    public Five2FiveOnNoRewardPush() {}
    
    
    private int _s2c_code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"s2c_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int s2c_code
    {
      get { return _s2c_code; }
      set { _s2c_code = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  /// <summary>
  /// 匹配失败
  /// </summary>
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Five2FiveMatchFailedPush")]
  public partial class Five2FiveMatchFailedPush : global::ProtoBuf.IExtensible
  {
    public Five2FiveMatchFailedPush() {}
    
    
    private int _s2c_code;
    /// <summary>
    /// 1、重新匹配2、需要重新点击匹配
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"s2c_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int s2c_code
    {
      get { return _s2c_code; }
      set { _s2c_code = value; }
    }
    
    private pomelo.five2five.Five2FiveMatchTime _five2FiveMatchTime = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"five2FiveMatchTime", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public pomelo.five2five.Five2FiveMatchTime five2FiveMatchTime
    {
      get { return _five2FiveMatchTime; }
      set { _five2FiveMatchTime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  /// <summary>
  /// 玩家索引信息
  /// </summary>
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Five2FiveIndexInfo")]
  public partial class Five2FiveIndexInfo : global::ProtoBuf.IExtensible
  {
    public Five2FiveIndexInfo() {}
    
    
    private string _playerId = "";
    /// <summary>
    /// 玩家ID
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    
    private string _playerName = "";
    /// <summary>
    /// 玩家名称
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"playerName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string playerName
    {
      get { return _playerName; }
      set { _playerName = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  /// <summary>
  /// 取消匹配推送
  /// </summary>
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Five2FiveLeaderCancelMatchPush")]
  public partial class Five2FiveLeaderCancelMatchPush : global::ProtoBuf.IExtensible
  {
    public Five2FiveLeaderCancelMatchPush() {}
    
    
    private int _s2c_code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"s2c_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int s2c_code
    {
      get { return _s2c_code; }
      set { _s2c_code = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  /// <summary>
  /// 队伍成员发生变化推送
  /// </summary>
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Five2FiveTeamChangePush")]
  public partial class Five2FiveTeamChangePush : global::ProtoBuf.IExtensible
  {
    public Five2FiveTeamChangePush() {}
    
    
    private int _s2c_code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"s2c_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int s2c_code
    {
      get { return _s2c_code; }
      set { _s2c_code = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  /// <summary>
  /// 匹配队列发生变化推送
  /// </summary>
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Five2FiveMatchPoolChangePush")]
  public partial class Five2FiveMatchPoolChangePush : global::ProtoBuf.IExtensible
  {
    public Five2FiveMatchPoolChangePush() {}
    
    
    private int _s2c_code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"s2c_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int s2c_code
    {
      get { return _s2c_code; }
      set { _s2c_code = value; }
    }
    
    private int _pre_number;
    /// <summary>
    /// 前方有多少人
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"pre_number", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int pre_number
    {
      get { return _pre_number; }
      set { _pre_number = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  /// <summary>
  /// 请求进入匹配队列结果推送
  /// </summary>
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Five2FiveApplyMatchResultPush")]
  public partial class Five2FiveApplyMatchResultPush : global::ProtoBuf.IExtensible
  {
    public Five2FiveApplyMatchResultPush() {}
    
    
    private int _s2c_code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"s2c_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int s2c_code
    {
      get { return _s2c_code; }
      set { _s2c_code = value; }
    }
    
    private pomelo.five2five.Five2FiveMatchTime _five2FiveMatchTime = null;
    /// <summary>
    /// 匹配时间
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"five2FiveMatchTime", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public pomelo.five2five.Five2FiveMatchTime five2FiveMatchTime
    {
      get { return _five2FiveMatchTime; }
      set { _five2FiveMatchTime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
}
  