//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// ***************************************************************************
// * 大逃杀
// ***************************************************************************

// Generated from: fleeHandler.proto
// Note: requires additional types generated from: common.proto
namespace pomelo.area
{
  
  //---------------------------------------------------------------------------------------
  /// <summary>
  /// 大逃杀主界面请求
  /// </summary>
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FleeInfoRequest")]
  public partial class FleeInfoRequest : global::ProtoBuf.IExtensible
  {
    public FleeInfoRequest() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  /// <summary>
  /// 段位奖励
  /// </summary>
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GradeReward")]
  public partial class GradeReward : global::ProtoBuf.IExtensible
  {
    public GradeReward() {}
    
    
    private int _gradeId;
    /// <summary>
    /// 段位ID
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"gradeId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int gradeId
    {
      get { return _gradeId; }
      set { _gradeId = value; }
    }
    
    private int _status;
    /// <summary>
    /// 领取状态 0-不可领取 1-可领取 2-已领取
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int status
    {
      get { return _status; }
      set { _status = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  /// <summary>
  /// 大逃杀主界面返回
  /// </summary>
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FleeInfoResponse")]
  public partial class FleeInfoResponse : global::ProtoBuf.IExtensible
  {
    public FleeInfoResponse() {}
    
    
    private int _s2c_code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"s2c_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int s2c_code
    {
      get { return _s2c_code; }
      set { _s2c_code = value; }
    }
    
    private string _s2c_msg = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"s2c_msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string s2c_msg
    {
      get { return _s2c_msg; }
      set { _s2c_msg = value; }
    }
    
    private int _currentRank = default(int);
    /// <summary>
    /// 当前排名为0表示没有排名
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"currentRank", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int currentRank
    {
      get { return _currentRank; }
      set { _currentRank = value; }
    }
    
    private int _maxRank = default(int);
    /// <summary>
    /// 历史最高排名为0表示没有排名
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"maxRank", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int maxRank
    {
      get { return _maxRank; }
      set { _maxRank = value; }
    }
    
    private int _grade = default(int);
    /// <summary>
    /// 段位
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"grade", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int grade
    {
      get { return _grade; }
      set { _grade = value; }
    }
    
    private int _maxGrade = default(int);
    /// <summary>
    /// 历史最高段位
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"maxGrade", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int maxGrade
    {
      get { return _maxGrade; }
      set { _maxGrade = value; }
    }
    
    private long _seasonEndTime = default(long);
    /// <summary>
    /// 赛季结束时间
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"seasonEndTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long seasonEndTime
    {
      get { return _seasonEndTime; }
      set { _seasonEndTime = value; }
    }
    
    private int _score = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"score", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int score
    {
      get { return _score; }
      set { _score = value; }
    }
    
    private readonly global::System.Collections.Generic.List<pomelo.area.GradeReward> _gradeRewards = new global::System.Collections.Generic.List<pomelo.area.GradeReward>();
    /// <summary>
    /// 段位奖励信息
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(9, Name=@"gradeRewards", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pomelo.area.GradeReward> gradeRewards
    {
      get { return _gradeRewards; }
    }
  
    
    private int _joinTime = default(int);
    /// <summary>
    /// 报名时间 0-没有报名
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"joinTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int joinTime
    {
      get { return _joinTime; }
      set { _joinTime = value; }
    }
    
    private int _avgMatchTime = default(int);
    /// <summary>
    /// 平均等待时间
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"avgMatchTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int avgMatchTime
    {
      get { return _avgMatchTime; }
      set { _avgMatchTime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  /// <summary>
  /// 领取段位奖励请求
  /// </summary>
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetRewardRequest")]
  public partial class GetRewardRequest : global::ProtoBuf.IExtensible
  {
    public GetRewardRequest() {}
    
    
    private int _gradeId;
    /// <summary>
    /// 段位ID
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"gradeId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int gradeId
    {
      get { return _gradeId; }
      set { _gradeId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  /// <summary>
  /// 领取段位奖励返回
  /// </summary>
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetRewardResponse")]
  public partial class GetRewardResponse : global::ProtoBuf.IExtensible
  {
    public GetRewardResponse() {}
    
    
    private int _s2c_code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"s2c_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int s2c_code
    {
      get { return _s2c_code; }
      set { _s2c_code = value; }
    }
    
    private string _s2c_msg = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"s2c_msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string s2c_msg
    {
      get { return _s2c_msg; }
      set { _s2c_msg = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  /// <summary>
  /// 查看战报请求
  /// </summary>
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FleeLookBtlReportRequest")]
  public partial class FleeLookBtlReportRequest : global::ProtoBuf.IExtensible
  {
    public FleeLookBtlReportRequest() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  /// <summary>
  /// 战报信息
  /// </summary>
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FleeBtlReport")]
  public partial class FleeBtlReport : global::ProtoBuf.IExtensible
  {
    public FleeBtlReport() {}
    
    
    private int _rank = default(int);
    /// <summary>
    /// 排名
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"rank", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int rank
    {
      get { return _rank; }
      set { _rank = value; }
    }
    
    private int _scoreChange = default(int);
    /// <summary>
    /// 积分变化
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"scoreChange", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int scoreChange
    {
      get { return _scoreChange; }
      set { _scoreChange = value; }
    }
    
    private string _createTime = "";
    /// <summary>
    /// 创建时间
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"createTime", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string createTime
    {
      get { return _createTime; }
      set { _createTime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  /// <summary>
  /// 查看战报返回
  /// </summary>
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FleeLookBtlReportResponse")]
  public partial class FleeLookBtlReportResponse : global::ProtoBuf.IExtensible
  {
    public FleeLookBtlReportResponse() {}
    
    
    private int _s2c_code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"s2c_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int s2c_code
    {
      get { return _s2c_code; }
      set { _s2c_code = value; }
    }
    
    private string _s2c_msg = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"s2c_msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string s2c_msg
    {
      get { return _s2c_msg; }
      set { _s2c_msg = value; }
    }
    
    private readonly global::System.Collections.Generic.List<pomelo.area.FleeBtlReport> _br = new global::System.Collections.Generic.List<pomelo.area.FleeBtlReport>();
    /// <summary>
    /// 战报
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(3, Name=@"br", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pomelo.area.FleeBtlReport> br
    {
      get { return _br; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  /// <summary>
  /// 请求进入大逃杀
  /// </summary>
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EnterFleeRequest")]
  public partial class EnterFleeRequest : global::ProtoBuf.IExtensible
  {
    public EnterFleeRequest() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  /// <summary>
  /// 进入大逃杀返回
  /// </summary>
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EnterFleeResponse")]
  public partial class EnterFleeResponse : global::ProtoBuf.IExtensible
  {
    public EnterFleeResponse() {}
    
    
    private int _s2c_code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"s2c_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int s2c_code
    {
      get { return _s2c_code; }
      set { _s2c_code = value; }
    }
    
    private string _s2c_msg = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"s2c_msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string s2c_msg
    {
      get { return _s2c_msg; }
      set { _s2c_msg = value; }
    }
    
    private int _avgMatchTime = default(int);
    /// <summary>
    /// 平均等待时间
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"avgMatchTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int avgMatchTime
    {
      get { return _avgMatchTime; }
      set { _avgMatchTime = value; }
    }
    
    private int _joinTime = default(int);
    /// <summary>
    /// 报名时间
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"joinTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int joinTime
    {
      get { return _joinTime; }
      set { _joinTime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  /// <summary>
  /// 取消匹配
  /// </summary>
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CancelMatchRequest")]
  public partial class CancelMatchRequest : global::ProtoBuf.IExtensible
  {
    public CancelMatchRequest() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  /// <summary>
  /// 取消匹配返回
  /// </summary>
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CancelMatchResponse")]
  public partial class CancelMatchResponse : global::ProtoBuf.IExtensible
  {
    public CancelMatchResponse() {}
    
    
    private int _s2c_code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"s2c_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int s2c_code
    {
      get { return _s2c_code; }
      set { _s2c_code = value; }
    }
    
    private string _s2c_msg = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"s2c_msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string s2c_msg
    {
      get { return _s2c_msg; }
      set { _s2c_msg = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  /// <summary>
  /// 大逃杀玩家信息
  /// </summary>
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FleeMatchMemberInfo")]
  public partial class FleeMatchMemberInfo : global::ProtoBuf.IExtensible
  {
    public FleeMatchMemberInfo() {}
    
    
    private string _playerId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    
    private int _playerPro;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"playerPro", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int playerPro
    {
      get { return _playerPro; }
      set { _playerPro = value; }
    }
    
    private int _playerLvl;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"playerLvl", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int playerLvl
    {
      get { return _playerLvl; }
      set { _playerLvl = value; }
    }
    
    private string _playerName;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"playerName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string playerName
    {
      get { return _playerName; }
      set { _playerName = value; }
    }
    
    private int _scoreChange;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"scoreChange", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int scoreChange
    {
      get { return _scoreChange; }
      set { _scoreChange = value; }
    }
    
    private int _killCount;
    /// <summary>
    /// 击杀数量
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"killCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int killCount
    {
      get { return _killCount; }
      set { _killCount = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  /// <summary>
  /// 自己被击杀推送
  /// </summary>
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OnFleeDeathPush")]
  public partial class OnFleeDeathPush : global::ProtoBuf.IExtensible
  {
    public OnFleeDeathPush() {}
    
    
    private int _s2c_code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"s2c_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int s2c_code
    {
      get { return _s2c_code; }
      set { _s2c_code = value; }
    }
    
    private int _outtime;
    /// <summary>
    /// 强制退出时间
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"outtime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int outtime
    {
      get { return _outtime; }
      set { _outtime = value; }
    }
    
    private int _rank;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"rank", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int rank
    {
      get { return _rank; }
      set { _rank = value; }
    }
    
    private int _scoreChange;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"scoreChange", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int scoreChange
    {
      get { return _scoreChange; }
      set { _scoreChange = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  /// <summary>
  /// 全场结束推送
  /// </summary>
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OnFleeEndPush")]
  public partial class OnFleeEndPush : global::ProtoBuf.IExtensible
  {
    public OnFleeEndPush() {}
    
    
    private int _s2c_code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"s2c_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int s2c_code
    {
      get { return _s2c_code; }
      set { _s2c_code = value; }
    }
    
    private int _outtime;
    /// <summary>
    /// 强制退出时间
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"outtime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int outtime
    {
      get { return _outtime; }
      set { _outtime = value; }
    }
    
    private readonly global::System.Collections.Generic.List<pomelo.area.FleeMatchMemberInfo> _ranks = new global::System.Collections.Generic.List<pomelo.area.FleeMatchMemberInfo>();
    [global::ProtoBuf.ProtoMember(3, Name=@"ranks", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pomelo.area.FleeMatchMemberInfo> ranks
    {
      get { return _ranks; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
}
  