//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// ***************************************************************************
// * 作者: 刘羿君
// * 创建时间: 2015-10-17
// * 用途: 道具处理器
// ***************************************************************************

// Generated from: itemHandler.proto
// Note: requires additional types generated from: common.proto
// Note: requires additional types generated from: item.proto
namespace pomelo.area
{
  
  //---------------------------------------------------------------------------------------
  /// <summary>
  /// 更新new角标
  /// </summary>
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"QueryItemStatusUpdateNotify")]
  public partial class QueryItemStatusUpdateNotify : global::ProtoBuf.IExtensible
  {
    public QueryItemStatusUpdateNotify() {}
    
    
    private int _index;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int index
    {
      get { return _index; }
      set { _index = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetAllEquipDetailsRequest")]
  public partial class GetAllEquipDetailsRequest : global::ProtoBuf.IExtensible
  {
    public GetAllEquipDetailsRequest() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetAllEquipDetailsResponse")]
  public partial class GetAllEquipDetailsResponse : global::ProtoBuf.IExtensible
  {
    public GetAllEquipDetailsResponse() {}
    
    
    private int _s2c_code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"s2c_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int s2c_code
    {
      get { return _s2c_code; }
      set { _s2c_code = value; }
    }
    
    private string _s2c_msg = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"s2c_msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string s2c_msg
    {
      get { return _s2c_msg; }
      set { _s2c_msg = value; }
    }
    
    private readonly global::System.Collections.Generic.List<pomelo.item.ItemDetail> _s2c_items = new global::System.Collections.Generic.List<pomelo.item.ItemDetail>();
    [global::ProtoBuf.ProtoMember(3, Name=@"s2c_items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pomelo.item.ItemDetail> s2c_items
    {
      get { return _s2c_items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  /// <summary>
  /// 请求合成公式
  /// </summary>
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetCombineFormulaRequest")]
  public partial class GetCombineFormulaRequest : global::ProtoBuf.IExtensible
  {
    public GetCombineFormulaRequest() {}
    
    
    private int _c2s_destID;
    /// <summary>
    /// 合成表里面的索引ID
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"c2s_destID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int c2s_destID
    {
      get { return _c2s_destID; }
      set { _c2s_destID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetCombineFormulaResponse")]
  public partial class GetCombineFormulaResponse : global::ProtoBuf.IExtensible
  {
    public GetCombineFormulaResponse() {}
    
    
    private int _s2c_code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"s2c_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int s2c_code
    {
      get { return _s2c_code; }
      set { _s2c_code = value; }
    }
    
    private string _s2c_msg = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"s2c_msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string s2c_msg
    {
      get { return _s2c_msg; }
      set { _s2c_msg = value; }
    }
    
    private pomelo.item.Combine _s2c_data = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"s2c_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public pomelo.item.Combine s2c_data
    {
      get { return _s2c_data; }
      set { _s2c_data = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  /// <summary>
  /// 请求合成
  /// </summary>
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CombineRequest")]
  public partial class CombineRequest : global::ProtoBuf.IExtensible
  {
    public CombineRequest() {}
    
    
    private int _c2s_destID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"c2s_destID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int c2s_destID
    {
      get { return _c2s_destID; }
      set { _c2s_destID = value; }
    }
    
    private int _c2s_num;
    /// <summary>
    /// 要合成的数量
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"c2s_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int c2s_num
    {
      get { return _c2s_num; }
      set { _c2s_num = value; }
    }
    
    private int _c2s_gridIndex = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"c2s_gridIndex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int c2s_gridIndex
    {
      get { return _c2s_gridIndex; }
      set { _c2s_gridIndex = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CombineResponse")]
  public partial class CombineResponse : global::ProtoBuf.IExtensible
  {
    public CombineResponse() {}
    
    
    private int _s2c_code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"s2c_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int s2c_code
    {
      get { return _s2c_code; }
      set { _s2c_code = value; }
    }
    
    private string _s2c_msg = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"s2c_msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string s2c_msg
    {
      get { return _s2c_msg; }
      set { _s2c_msg = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ItemDetailPush")]
  public partial class ItemDetailPush : global::ProtoBuf.IExtensible
  {
    public ItemDetailPush() {}
    
    
    private int _s2c_code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"s2c_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int s2c_code
    {
      get { return _s2c_code; }
      set { _s2c_code = value; }
    }
    
    private readonly global::System.Collections.Generic.List<pomelo.item.ItemDetail> _s2c_data = new global::System.Collections.Generic.List<pomelo.item.ItemDetail>();
    [global::ProtoBuf.ProtoMember(2, Name=@"s2c_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pomelo.item.ItemDetail> s2c_data
    {
      get { return _s2c_data; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  /// <summary>
  /// 计数道具变化推送
  /// </summary>
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CountItemChangePush")]
  public partial class CountItemChangePush : global::ProtoBuf.IExtensible
  {
    public CountItemChangePush() {}
    
    
    private int _s2c_code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"s2c_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int s2c_code
    {
      get { return _s2c_code; }
      set { _s2c_code = value; }
    }
    
    private readonly global::System.Collections.Generic.List<pomelo.item.CountItem> _s2c_data = new global::System.Collections.Generic.List<pomelo.item.CountItem>();
    [global::ProtoBuf.ProtoMember(2, Name=@"s2c_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pomelo.item.CountItem> s2c_data
    {
      get { return _s2c_data; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FishItemPush")]
  public partial class FishItemPush : global::ProtoBuf.IExtensible
  {
    public FishItemPush() {}
    
    
    private int _s2c_code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"s2c_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int s2c_code
    {
      get { return _s2c_code; }
      set { _s2c_code = value; }
    }
    
    private readonly global::System.Collections.Generic.List<pomelo.item.MiniItem> _s2c_item = new global::System.Collections.Generic.List<pomelo.item.MiniItem>();
    [global::ProtoBuf.ProtoMember(2, Name=@"s2c_item", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pomelo.item.MiniItem> s2c_item
    {
      get { return _s2c_item; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RewardItemPush")]
  public partial class RewardItemPush : global::ProtoBuf.IExtensible
  {
    public RewardItemPush() {}
    
    
    private int _s2c_code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"s2c_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int s2c_code
    {
      get { return _s2c_code; }
      set { _s2c_code = value; }
    }
    
    private readonly global::System.Collections.Generic.List<pomelo.item.MiniItem> _s2c_item = new global::System.Collections.Generic.List<pomelo.item.MiniItem>();
    [global::ProtoBuf.ProtoMember(2, Name=@"s2c_item", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pomelo.item.MiniItem> s2c_item
    {
      get { return _s2c_item; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
}
  