//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// ***************************************************************************
// * 作者= jjr
// * 创建时间= 2017-03-27
// * 用途= 排行榜
// ***************************************************************************/

// Generated from: leaderBoardHandler.proto
// Note: requires additional types generated from: common.proto
namespace pomelo.area
{
  
  //---------------------------------------------------------------------------------------
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LeaderBoardData")]
  public partial class LeaderBoardData : global::ProtoBuf.IExtensible
  {
    public LeaderBoardData() {}
    
    
    private readonly global::System.Collections.Generic.List<string> _contents = new global::System.Collections.Generic.List<string>();
    /// <summary>
    /// 客户端显示字段需和客户端相对应，约定数组第一个传rank排名
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(1, Name=@"contents", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> contents
    {
      get { return _contents; }
    }
  
    
    private readonly global::System.Collections.Generic.List<pomelo.Avatar> _avatars = new global::System.Collections.Generic.List<pomelo.Avatar>();
    /// <summary>
    /// 人物avatar 除公会,宠物,坐骑都有 本人排名信息没有
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(2, Name=@"avatars", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pomelo.Avatar> avatars
    {
      get { return _avatars; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  /// <summary>
  /// 排行榜公会信息结构
  /// </summary>
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RankGuildInfo")]
  public partial class RankGuildInfo : global::ProtoBuf.IExtensible
  {
    public RankGuildInfo() {}
    
    
    private string _guildId = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"guildId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string guildId
    {
      get { return _guildId; }
      set { _guildId = value; }
    }
    
    private string _guildIcon = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"guildIcon", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string guildIcon
    {
      get { return _guildIcon; }
      set { _guildIcon = value; }
    }
    
    private string _guildMaster = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"guildMaster", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string guildMaster
    {
      get { return _guildMaster; }
      set { _guildMaster = value; }
    }
    
    private int _guildLevel = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"guildLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int guildLevel
    {
      get { return _guildLevel; }
      set { _guildLevel = value; }
    }
    
    private int _curMember = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"curMember", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int curMember
    {
      get { return _curMember; }
      set { _curMember = value; }
    }
    
    private int _maxMember = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"maxMember", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int maxMember
    {
      get { return _maxMember; }
      set { _maxMember = value; }
    }
    
    private int _fund = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"fund", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int fund
    {
      get { return _fund; }
      set { _fund = value; }
    }
    
    private string _notice = "";
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"notice", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string notice
    {
      get { return _notice; }
      set { _notice = value; }
    }
    
    private int _guildMasterPro = default(int);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"guildMasterPro", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int guildMasterPro
    {
      get { return _guildMasterPro; }
      set { _guildMasterPro = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  /// <summary>
  /// 获取排行榜  (请求)
  /// </summary>
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LeaderBoardRequest")]
  public partial class LeaderBoardRequest : global::ProtoBuf.IExtensible
  {
    public LeaderBoardRequest() {}
    
    
    private int _c2s_kind;
    /// <summary>
    /// 排行榜类型
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"c2s_kind", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int c2s_kind
    {
      get { return _c2s_kind; }
      set { _c2s_kind = value; }
    }
    
    private int _c2s_season = default(int);
    /// <summary>
    /// 赛季类型  -1：没有赛季概念  0 上一赛季  1 当前赛季
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"c2s_season", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int c2s_season
    {
      get { return _c2s_season; }
      set { _c2s_season = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  /// <summary>
  /// 获取排行榜 (返回)
  /// </summary>
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LeaderBoardResponse")]
  public partial class LeaderBoardResponse : global::ProtoBuf.IExtensible
  {
    public LeaderBoardResponse() {}
    
    
    private int _s2c_code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"s2c_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int s2c_code
    {
      get { return _s2c_code; }
      set { _s2c_code = value; }
    }
    
    private string _s2c_msg = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"s2c_msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string s2c_msg
    {
      get { return _s2c_msg; }
      set { _s2c_msg = value; }
    }
    
    private readonly global::System.Collections.Generic.List<pomelo.area.LeaderBoardData> _s2c_lists = new global::System.Collections.Generic.List<pomelo.area.LeaderBoardData>();
    [global::ProtoBuf.ProtoMember(3, Name=@"s2c_lists", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pomelo.area.LeaderBoardData> s2c_lists
    {
      get { return _s2c_lists; }
    }
  
    
    private pomelo.area.LeaderBoardData _s2c_myData = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"s2c_myData", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public pomelo.area.LeaderBoardData s2c_myData
    {
      get { return _s2c_myData; }
      set { _s2c_myData = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  /// <summary>
  /// 获取公会信息 (请求)
  /// </summary>
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GuildInfoRequest")]
  public partial class GuildInfoRequest : global::ProtoBuf.IExtensible
  {
    public GuildInfoRequest() {}
    
    
    private string _c2s_guildId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"c2s_guildId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string c2s_guildId
    {
      get { return _c2s_guildId; }
      set { _c2s_guildId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  /// <summary>
  /// 获取公会信息 (返回)
  /// </summary>
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GuildInfoResponse")]
  public partial class GuildInfoResponse : global::ProtoBuf.IExtensible
  {
    public GuildInfoResponse() {}
    
    
    private int _s2c_code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"s2c_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int s2c_code
    {
      get { return _s2c_code; }
      set { _s2c_code = value; }
    }
    
    private string _s2c_msg = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"s2c_msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string s2c_msg
    {
      get { return _s2c_msg; }
      set { _s2c_msg = value; }
    }
    
    private pomelo.area.RankGuildInfo _s2c_data = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"s2c_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public pomelo.area.RankGuildInfo s2c_data
    {
      get { return _s2c_data; }
      set { _s2c_data = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"WorShipRequest")]
  public partial class WorShipRequest : global::ProtoBuf.IExtensible
  {
    public WorShipRequest() {}
    
    
    private int _c2s_type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"c2s_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int c2s_type
    {
      get { return _c2s_type; }
      set { _c2s_type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"WorShipResponse")]
  public partial class WorShipResponse : global::ProtoBuf.IExtensible
  {
    public WorShipResponse() {}
    
    
    private int _s2c_code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"s2c_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int s2c_code
    {
      get { return _s2c_code; }
      set { _s2c_code = value; }
    }
    
    private string _s2c_msg = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"s2c_msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string s2c_msg
    {
      get { return _s2c_msg; }
      set { _s2c_msg = value; }
    }
    
    private readonly global::System.Collections.Generic.List<string> _s2c_awards = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(3, Name=@"s2c_awards", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> s2c_awards
    {
      get { return _s2c_awards; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"WorldLevelInfoRequest")]
  public partial class WorldLevelInfoRequest : global::ProtoBuf.IExtensible
  {
    public WorldLevelInfoRequest() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"WorldLevelInfo")]
  public partial class WorldLevelInfo : global::ProtoBuf.IExtensible
  {
    public WorldLevelInfo() {}
    
    
    private string _worldLevelId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"worldLevelId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string worldLevelId
    {
      get { return _worldLevelId; }
      set { _worldLevelId = value; }
    }
    
    private string _worldLevelName;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"worldLevelName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string worldLevelName
    {
      get { return _worldLevelName; }
      set { _worldLevelName = value; }
    }
    
    private int _worldLevel;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"worldLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int worldLevel
    {
      get { return _worldLevel; }
      set { _worldLevel = value; }
    }
    
    private int _worldUpLevel;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"worldUpLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int worldUpLevel
    {
      get { return _worldUpLevel; }
      set { _worldUpLevel = value; }
    }
    
    private readonly global::System.Collections.Generic.List<pomelo.Avatar> _avatars = new global::System.Collections.Generic.List<pomelo.Avatar>();
    [global::ProtoBuf.ProtoMember(5, Name=@"avatars", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pomelo.Avatar> avatars
    {
      get { return _avatars; }
    }
  
    
    private int _addExp;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"addExp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int addExp
    {
      get { return _addExp; }
      set { _addExp = value; }
    }
    
    private int _worShipTimes;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"worShipTimes", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int worShipTimes
    {
      get { return _worShipTimes; }
      set { _worShipTimes = value; }
    }
    
    private int _maxWorShipTimes;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"maxWorShipTimes", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int maxWorShipTimes
    {
      get { return _maxWorShipTimes; }
      set { _maxWorShipTimes = value; }
    }
    
    private int _worldLevelPro;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"worldLevelPro", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int worldLevelPro
    {
      get { return _worldLevelPro; }
      set { _worldLevelPro = value; }
    }
    
    private string _rank1stGuildName = "";
    /// <summary>
    /// 第一名玩家的公会名
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"rank1stGuildName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string rank1stGuildName
    {
      get { return _rank1stGuildName; }
      set { _rank1stGuildName = value; }
    }
    
    private int _rank1stFight = default(int);
    /// <summary>
    /// 第一名玩家的战力
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"rank1stFight", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int rank1stFight
    {
      get { return _rank1stFight; }
      set { _rank1stFight = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"WorldLevelInfoResponse")]
  public partial class WorldLevelInfoResponse : global::ProtoBuf.IExtensible
  {
    public WorldLevelInfoResponse() {}
    
    
    private int _s2c_code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"s2c_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int s2c_code
    {
      get { return _s2c_code; }
      set { _s2c_code = value; }
    }
    
    private string _s2c_msg = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"s2c_msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string s2c_msg
    {
      get { return _s2c_msg; }
      set { _s2c_msg = value; }
    }
    
    private pomelo.area.WorldLevelInfo _s2c_data;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"s2c_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public pomelo.area.WorldLevelInfo s2c_data
    {
      get { return _s2c_data; }
      set { _s2c_data = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
}
  