//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// ***************************************************************************
// * 作者= 于洋
// * 创建时间= 2016-10-25
// * 用途= 限时活动
// ***************************************************************************

// Generated from: limitTimeActivityHandler.proto
// Note: requires additional types generated from: common.proto
namespace pomelo.area
{
  
  //---------------------------------------------------------------------------------------
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ActivityInfo")]
  public partial class ActivityInfo : global::ProtoBuf.IExtensible
  {
    public ActivityInfo() {}
    
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    
    private int _isOpen;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"isOpen", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int isOpen
    {
      get { return _isOpen; }
      set { _isOpen = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetLimitTimeActivityInfoRequest")]
  public partial class GetLimitTimeActivityInfoRequest : global::ProtoBuf.IExtensible
  {
    public GetLimitTimeActivityInfoRequest() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetLimitTimeActivityInfoResponse")]
  public partial class GetLimitTimeActivityInfoResponse : global::ProtoBuf.IExtensible
  {
    public GetLimitTimeActivityInfoResponse() {}
    
    
    private int _s2c_code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"s2c_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int s2c_code
    {
      get { return _s2c_code; }
      set { _s2c_code = value; }
    }
    
    private string _s2c_msg = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"s2c_msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string s2c_msg
    {
      get { return _s2c_msg; }
      set { _s2c_msg = value; }
    }
    
    private readonly global::System.Collections.Generic.List<pomelo.area.ActivityInfo> _s2c_ltActivity = new global::System.Collections.Generic.List<pomelo.area.ActivityInfo>();
    [global::ProtoBuf.ProtoMember(3, Name=@"s2c_ltActivity", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pomelo.area.ActivityInfo> s2c_ltActivity
    {
      get { return _s2c_ltActivity; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LTActivityInfoPush")]
  public partial class LTActivityInfoPush : global::ProtoBuf.IExtensible
  {
    public LTActivityInfoPush() {}
    
    
    private int _s2c_code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"s2c_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int s2c_code
    {
      get { return _s2c_code; }
      set { _s2c_code = value; }
    }
    
    private readonly global::System.Collections.Generic.List<pomelo.area.ActivityInfo> _s2c_ltActivity = new global::System.Collections.Generic.List<pomelo.area.ActivityInfo>();
    [global::ProtoBuf.ProtoMember(2, Name=@"s2c_ltActivity", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pomelo.area.ActivityInfo> s2c_ltActivity
    {
      get { return _s2c_ltActivity; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
}
  