//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// ***************************************************************************
// * 作者= 卢松洁
// * 创建时间= 2015-08-27
// * 用途= 邮件处理器
// ***************************************************************************

// Generated from: mailHandler.proto
// Note: requires additional types generated from: common.proto
// Note: requires additional types generated from: item.proto
namespace pomelo.area
{
  
  //---------------------------------------------------------------------------------------
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MailGetAllRequest")]
  public partial class MailGetAllRequest : global::ProtoBuf.IExtensible
  {
    public MailGetAllRequest() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MailReadNotify")]
  public partial class MailReadNotify : global::ProtoBuf.IExtensible
  {
    public MailReadNotify() {}
    
    
    private readonly global::System.Collections.Generic.List<string> _c2s_id = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(1, Name=@"c2s_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> c2s_id
    {
      get { return _c2s_id; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MailSendMailRequest")]
  public partial class MailSendMailRequest : global::ProtoBuf.IExtensible
  {
    public MailSendMailRequest() {}
    
    
    private string _toPlayerId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"toPlayerId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string toPlayerId
    {
      get { return _toPlayerId; }
      set { _toPlayerId = value; }
    }
    
    private string _mailTitle;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"mailTitle", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string mailTitle
    {
      get { return _mailTitle; }
      set { _mailTitle = value; }
    }
    
    private string _mailText;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"mailText", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string mailText
    {
      get { return _mailText; }
      set { _mailText = value; }
    }
    
    private int _mailRead;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"mailRead", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int mailRead
    {
      get { return _mailRead; }
      set { _mailRead = value; }
    }
    
    private string _toPlayerName = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"toPlayerName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string toPlayerName
    {
      get { return _toPlayerName; }
      set { _toPlayerName = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MailGetAttachmentRequest")]
  public partial class MailGetAttachmentRequest : global::ProtoBuf.IExtensible
  {
    public MailGetAttachmentRequest() {}
    
    
    private string _c2s_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"c2s_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string c2s_id
    {
      get { return _c2s_id; }
      set { _c2s_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MailGetAttachmentOneKeyRequest")]
  public partial class MailGetAttachmentOneKeyRequest : global::ProtoBuf.IExtensible
  {
    public MailGetAttachmentOneKeyRequest() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MailDeleteRequest")]
  public partial class MailDeleteRequest : global::ProtoBuf.IExtensible
  {
    public MailDeleteRequest() {}
    
    
    private string _c2s_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"c2s_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string c2s_id
    {
      get { return _c2s_id; }
      set { _c2s_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MailDeleteOneKeyRequest")]
  public partial class MailDeleteOneKeyRequest : global::ProtoBuf.IExtensible
  {
    public MailDeleteOneKeyRequest() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MailSendTestNotify")]
  public partial class MailSendTestNotify : global::ProtoBuf.IExtensible
  {
    public MailSendTestNotify() {}
    
    
    private int _c2s_mailId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"c2s_mailId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int c2s_mailId
    {
      get { return _c2s_mailId; }
      set { _c2s_mailId = value; }
    }
    
    private string _c2s_tcCode;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"c2s_tcCode", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string c2s_tcCode
    {
      get { return _c2s_tcCode; }
      set { _c2s_tcCode = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Mail")]
  public partial class Mail : global::ProtoBuf.IExtensible
  {
    public Mail() {}
    
    
    private string _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string id
    {
      get { return _id; }
      set { _id = value; }
    }
    
    private int _mailId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"mailId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int mailId
    {
      get { return _mailId; }
      set { _mailId = value; }
    }
    
    private int _mailType;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"mailType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int mailType
    {
      get { return _mailType; }
      set { _mailType = value; }
    }
    
    private int _mailIcon;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"mailIcon", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int mailIcon
    {
      get { return _mailIcon; }
      set { _mailIcon = value; }
    }
    
    private string _mailSender;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"mailSender", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string mailSender
    {
      get { return _mailSender; }
      set { _mailSender = value; }
    }
    
    private string _mailTitle;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"mailTitle", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string mailTitle
    {
      get { return _mailTitle; }
      set { _mailTitle = value; }
    }
    
    private string _mailText;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"mailText", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string mailText
    {
      get { return _mailText; }
      set { _mailText = value; }
    }
    
    private string _createTime;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"createTime", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string createTime
    {
      get { return _createTime; }
      set { _createTime = value; }
    }
    
    private int _status;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int status
    {
      get { return _status; }
      set { _status = value; }
    }
    
    private int _mailRead;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"mailRead", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int mailRead
    {
      get { return _mailRead; }
      set { _mailRead = value; }
    }
    
    private int _hadAttach;
    [global::ProtoBuf.ProtoMember(11, IsRequired = true, Name=@"hadAttach", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int hadAttach
    {
      get { return _hadAttach; }
      set { _hadAttach = value; }
    }
    
    private readonly global::System.Collections.Generic.List<pomelo.item.MiniItem> _attachment = new global::System.Collections.Generic.List<pomelo.item.MiniItem>();
    [global::ProtoBuf.ProtoMember(12, Name=@"attachment", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pomelo.item.MiniItem> attachment
    {
      get { return _attachment; }
    }
  
    
    private string _mailSenderId = "";
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"mailSenderId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string mailSenderId
    {
      get { return _mailSenderId; }
      set { _mailSenderId = value; }
    }
    
    private readonly global::System.Collections.Generic.List<pomelo.item.EarItemDetail> _itemEar = new global::System.Collections.Generic.List<pomelo.item.EarItemDetail>();
    [global::ProtoBuf.ProtoMember(14, Name=@"itemEar", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pomelo.item.EarItemDetail> itemEar
    {
      get { return _itemEar; }
    }
  
    
    private readonly global::System.Collections.Generic.List<pomelo.item.ItemDetail> _newAttachment = new global::System.Collections.Generic.List<pomelo.item.ItemDetail>();
    /// <summary>
    /// 新版本附件
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(15, Name=@"newAttachment", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pomelo.item.ItemDetail> newAttachment
    {
      get { return _newAttachment; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MailGetAllResponse")]
  public partial class MailGetAllResponse : global::ProtoBuf.IExtensible
  {
    public MailGetAllResponse() {}
    
    
    private int _s2c_code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"s2c_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int s2c_code
    {
      get { return _s2c_code; }
      set { _s2c_code = value; }
    }
    
    private string _s2c_msg = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"s2c_msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string s2c_msg
    {
      get { return _s2c_msg; }
      set { _s2c_msg = value; }
    }
    
    private readonly global::System.Collections.Generic.List<pomelo.area.Mail> _mails = new global::System.Collections.Generic.List<pomelo.area.Mail>();
    [global::ProtoBuf.ProtoMember(3, Name=@"mails", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pomelo.area.Mail> mails
    {
      get { return _mails; }
    }
  
    
    private int _s2c_maxMailNum;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"s2c_maxMailNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int s2c_maxMailNum
    {
      get { return _s2c_maxMailNum; }
      set { _s2c_maxMailNum = value; }
    }
    
    private int _s2c_maxWordNum;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"s2c_maxWordNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int s2c_maxWordNum
    {
      get { return _s2c_maxWordNum; }
      set { _s2c_maxWordNum = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OnGetMailPush")]
  public partial class OnGetMailPush : global::ProtoBuf.IExtensible
  {
    public OnGetMailPush() {}
    
    
    private int _s2c_code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"s2c_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int s2c_code
    {
      get { return _s2c_code; }
      set { _s2c_code = value; }
    }
    
    private readonly global::System.Collections.Generic.List<pomelo.area.Mail> _mails = new global::System.Collections.Generic.List<pomelo.area.Mail>();
    [global::ProtoBuf.ProtoMember(2, Name=@"mails", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pomelo.area.Mail> mails
    {
      get { return _mails; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MailSendMailResponse")]
  public partial class MailSendMailResponse : global::ProtoBuf.IExtensible
  {
    public MailSendMailResponse() {}
    
    
    private int _s2c_code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"s2c_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int s2c_code
    {
      get { return _s2c_code; }
      set { _s2c_code = value; }
    }
    
    private string _s2c_msg = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"s2c_msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string s2c_msg
    {
      get { return _s2c_msg; }
      set { _s2c_msg = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MailDeleteResponse")]
  public partial class MailDeleteResponse : global::ProtoBuf.IExtensible
  {
    public MailDeleteResponse() {}
    
    
    private int _s2c_code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"s2c_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int s2c_code
    {
      get { return _s2c_code; }
      set { _s2c_code = value; }
    }
    
    private string _s2c_msg = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"s2c_msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string s2c_msg
    {
      get { return _s2c_msg; }
      set { _s2c_msg = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MailDeleteOneKeyResponse")]
  public partial class MailDeleteOneKeyResponse : global::ProtoBuf.IExtensible
  {
    public MailDeleteOneKeyResponse() {}
    
    
    private int _s2c_code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"s2c_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int s2c_code
    {
      get { return _s2c_code; }
      set { _s2c_code = value; }
    }
    
    private string _s2c_msg = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"s2c_msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string s2c_msg
    {
      get { return _s2c_msg; }
      set { _s2c_msg = value; }
    }
    
    private readonly global::System.Collections.Generic.List<string> _s2c_ids = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(3, Name=@"s2c_ids", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> s2c_ids
    {
      get { return _s2c_ids; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MailGetAttachmentResponse")]
  public partial class MailGetAttachmentResponse : global::ProtoBuf.IExtensible
  {
    public MailGetAttachmentResponse() {}
    
    
    private int _s2c_code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"s2c_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int s2c_code
    {
      get { return _s2c_code; }
      set { _s2c_code = value; }
    }
    
    private string _s2c_msg = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"s2c_msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string s2c_msg
    {
      get { return _s2c_msg; }
      set { _s2c_msg = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MailGetAttachmentOneKeyResponse")]
  public partial class MailGetAttachmentOneKeyResponse : global::ProtoBuf.IExtensible
  {
    public MailGetAttachmentOneKeyResponse() {}
    
    
    private int _s2c_code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"s2c_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int s2c_code
    {
      get { return _s2c_code; }
      set { _s2c_code = value; }
    }
    
    private string _s2c_msg = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"s2c_msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string s2c_msg
    {
      get { return _s2c_msg; }
      set { _s2c_msg = value; }
    }
    
    private readonly global::System.Collections.Generic.List<string> _s2c_ids = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(3, Name=@"s2c_ids", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> s2c_ids
    {
      get { return _s2c_ids; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
}
  