//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// ***************************************************************************
// * 作者= 卢松洁
// * 创建时间= 2015-08-27
// * 用途= 离线奖励处理器
// ***************************************************************************

// Generated from: offlineAwardHandler.proto
namespace pomelo.area
{
  
  //---------------------------------------------------------------------------------------
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OfflineAwardItem")]
  public partial class OfflineAwardItem : global::ProtoBuf.IExtensible
  {
    public OfflineAwardItem() {}
    
    
    private int _templateId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"templateId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int templateId
    {
      get { return _templateId; }
      set { _templateId = value; }
    }
    
    private int _picId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"picId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int picId
    {
      get { return _picId; }
      set { _picId = value; }
    }
    
    private string _name;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    
    private int _num;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int num
    {
      get { return _num; }
      set { _num = value; }
    }
    
    private int _quality;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"quality", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int quality
    {
      get { return _quality; }
      set { _quality = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OfflineAward")]
  public partial class OfflineAward : global::ProtoBuf.IExtensible
  {
    public OfflineAward() {}
    
    
    private int _flag;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"flag", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int flag
    {
      get { return _flag; }
      set { _flag = value; }
    }
    
    private int _areaId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"areaId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int areaId
    {
      get { return _areaId; }
      set { _areaId = value; }
    }
    
    private int _gold;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"gold", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int gold
    {
      get { return _gold; }
      set { _gold = value; }
    }
    
    private int _exp;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"exp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int exp
    {
      get { return _exp; }
      set { _exp = value; }
    }
    
    private readonly global::System.Collections.Generic.List<pomelo.area.OfflineAwardItem> _offlineAwardItems = new global::System.Collections.Generic.List<pomelo.area.OfflineAwardItem>();
    [global::ProtoBuf.ProtoMember(5, Name=@"offlineAwardItems", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pomelo.area.OfflineAwardItem> offlineAwardItems
    {
      get { return _offlineAwardItems; }
    }
  
    
    private int _offlineTime;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"offlineTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int offlineTime
    {
      get { return _offlineTime; }
      set { _offlineTime = value; }
    }
    
    private int _v1Cost;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"v1Cost", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int v1Cost
    {
      get { return _v1Cost; }
      set { _v1Cost = value; }
    }
    
    private int _v1BoxNum;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"v1BoxNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int v1BoxNum
    {
      get { return _v1BoxNum; }
      set { _v1BoxNum = value; }
    }
    
    private int _v5Cost;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"v5Cost", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int v5Cost
    {
      get { return _v5Cost; }
      set { _v5Cost = value; }
    }
    
    private int _v5BoxNum;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"v5BoxNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int v5BoxNum
    {
      get { return _v5BoxNum; }
      set { _v5BoxNum = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OfflineAwardDetail")]
  public partial class OfflineAwardDetail : global::ProtoBuf.IExtensible
  {
    public OfflineAwardDetail() {}
    
    
    private string _areaName;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"areaName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string areaName
    {
      get { return _areaName; }
      set { _areaName = value; }
    }
    
    private int _offlineTime;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"offlineTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int offlineTime
    {
      get { return _offlineTime; }
      set { _offlineTime = value; }
    }
    
    private int _gold;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"gold", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int gold
    {
      get { return _gold; }
      set { _gold = value; }
    }
    
    private int _exp;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"exp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int exp
    {
      get { return _exp; }
      set { _exp = value; }
    }
    
    private int _goldPerHour;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"goldPerHour", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int goldPerHour
    {
      get { return _goldPerHour; }
      set { _goldPerHour = value; }
    }
    
    private int _expPerHour;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"expPerHour", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int expPerHour
    {
      get { return _expPerHour; }
      set { _expPerHour = value; }
    }
    
    private readonly global::System.Collections.Generic.List<pomelo.area.OfflineAwardItem> _offlineAwardItems = new global::System.Collections.Generic.List<pomelo.area.OfflineAwardItem>();
    [global::ProtoBuf.ProtoMember(7, Name=@"offlineAwardItems", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pomelo.area.OfflineAwardItem> offlineAwardItems
    {
      get { return _offlineAwardItems; }
    }
  
    
    private int _v1Cost;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"v1Cost", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int v1Cost
    {
      get { return _v1Cost; }
      set { _v1Cost = value; }
    }
    
    private int _v1BoxNum;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"v1BoxNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int v1BoxNum
    {
      get { return _v1BoxNum; }
      set { _v1BoxNum = value; }
    }
    
    private int _v5Cost;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"v5Cost", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int v5Cost
    {
      get { return _v5Cost; }
      set { _v5Cost = value; }
    }
    
    private int _v5BoxNum;
    [global::ProtoBuf.ProtoMember(11, IsRequired = true, Name=@"v5BoxNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int v5BoxNum
    {
      get { return _v5BoxNum; }
      set { _v5BoxNum = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OfflineAreaDetail")]
  public partial class OfflineAreaDetail : global::ProtoBuf.IExtensible
  {
    public OfflineAreaDetail() {}
    
    
    private string _name;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    
    private int _id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    
    private int _minLevel;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"minLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int minLevel
    {
      get { return _minLevel; }
      set { _minLevel = value; }
    }
    
    private int _maxLevel;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"maxLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int maxLevel
    {
      get { return _maxLevel; }
      set { _maxLevel = value; }
    }
    
    private int _minFightPower;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"minFightPower", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int minFightPower
    {
      get { return _minFightPower; }
      set { _minFightPower = value; }
    }
    
    private int _goldPerHour;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"goldPerHour", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int goldPerHour
    {
      get { return _goldPerHour; }
      set { _goldPerHour = value; }
    }
    
    private int _expPerHour;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"expPerHour", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int expPerHour
    {
      get { return _expPerHour; }
      set { _expPerHour = value; }
    }
    
    private readonly global::System.Collections.Generic.List<pomelo.area.OfflineAwardItem> _offlineAwardItems = new global::System.Collections.Generic.List<pomelo.area.OfflineAwardItem>();
    [global::ProtoBuf.ProtoMember(8, Name=@"offlineAwardItems", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pomelo.area.OfflineAwardItem> offlineAwardItems
    {
      get { return _offlineAwardItems; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SetOfflineAreaIdRequest")]
  public partial class SetOfflineAreaIdRequest : global::ProtoBuf.IExtensible
  {
    public SetOfflineAreaIdRequest() {}
    
    
    private int _c2s_areaId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"c2s_areaId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int c2s_areaId
    {
      get { return _c2s_areaId; }
      set { _c2s_areaId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"QueryOfflineAwardRequest")]
  public partial class QueryOfflineAwardRequest : global::ProtoBuf.IExtensible
  {
    public QueryOfflineAwardRequest() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetOfflineAwardRequest")]
  public partial class GetOfflineAwardRequest : global::ProtoBuf.IExtensible
  {
    public GetOfflineAwardRequest() {}
    
    
    private string _c2s_type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"c2s_type", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string c2s_type
    {
      get { return _c2s_type; }
      set { _c2s_type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetCurrentOfflineAreaRequest")]
  public partial class GetCurrentOfflineAreaRequest : global::ProtoBuf.IExtensible
  {
    public GetCurrentOfflineAreaRequest() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SetOfflineAreaIdResponse")]
  public partial class SetOfflineAreaIdResponse : global::ProtoBuf.IExtensible
  {
    public SetOfflineAreaIdResponse() {}
    
    
    private int _s2c_code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"s2c_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int s2c_code
    {
      get { return _s2c_code; }
      set { _s2c_code = value; }
    }
    
    private string _s2c_msg = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"s2c_msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string s2c_msg
    {
      get { return _s2c_msg; }
      set { _s2c_msg = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"QueryOfflineAwardResponse")]
  public partial class QueryOfflineAwardResponse : global::ProtoBuf.IExtensible
  {
    public QueryOfflineAwardResponse() {}
    
    
    private int _s2c_code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"s2c_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int s2c_code
    {
      get { return _s2c_code; }
      set { _s2c_code = value; }
    }
    
    private string _s2c_msg = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"s2c_msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string s2c_msg
    {
      get { return _s2c_msg; }
      set { _s2c_msg = value; }
    }
    
    private pomelo.area.OfflineAward _offlineAward = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"offlineAward", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public pomelo.area.OfflineAward offlineAward
    {
      get { return _offlineAward; }
      set { _offlineAward = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetOfflineAwardResponse")]
  public partial class GetOfflineAwardResponse : global::ProtoBuf.IExtensible
  {
    public GetOfflineAwardResponse() {}
    
    
    private int _s2c_code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"s2c_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int s2c_code
    {
      get { return _s2c_code; }
      set { _s2c_code = value; }
    }
    
    private string _s2c_msg = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"s2c_msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string s2c_msg
    {
      get { return _s2c_msg; }
      set { _s2c_msg = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetCurrentOfflineAreaResponse")]
  public partial class GetCurrentOfflineAreaResponse : global::ProtoBuf.IExtensible
  {
    public GetCurrentOfflineAreaResponse() {}
    
    
    private int _s2c_code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"s2c_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int s2c_code
    {
      get { return _s2c_code; }
      set { _s2c_code = value; }
    }
    
    private string _s2c_msg = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"s2c_msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string s2c_msg
    {
      get { return _s2c_msg; }
      set { _s2c_msg = value; }
    }
    
    private string _name = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    
    private int _minLevel = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"minLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int minLevel
    {
      get { return _minLevel; }
      set { _minLevel = value; }
    }
    
    private int _maxLevel = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"maxLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int maxLevel
    {
      get { return _maxLevel; }
      set { _maxLevel = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"QueryAllAreasRequest")]
  public partial class QueryAllAreasRequest : global::ProtoBuf.IExtensible
  {
    public QueryAllAreasRequest() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"QueryAllAreasResponse")]
  public partial class QueryAllAreasResponse : global::ProtoBuf.IExtensible
  {
    public QueryAllAreasResponse() {}
    
    
    private int _s2c_code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"s2c_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int s2c_code
    {
      get { return _s2c_code; }
      set { _s2c_code = value; }
    }
    
    private string _s2c_msg = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"s2c_msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string s2c_msg
    {
      get { return _s2c_msg; }
      set { _s2c_msg = value; }
    }
    
    private readonly global::System.Collections.Generic.List<pomelo.area.OfflineAreaDetail> _s2c_areasDetail = new global::System.Collections.Generic.List<pomelo.area.OfflineAreaDetail>();
    [global::ProtoBuf.ProtoMember(3, Name=@"s2c_areasDetail", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pomelo.area.OfflineAreaDetail> s2c_areasDetail
    {
      get { return _s2c_areasDetail; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
}
  