//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// ***************************************************************************
// * 作者= jjr
// * 创建时间= 2017-03-15
// * 用途= 角色数据
// ***************************************************************************/

// Generated from: player.proto
// Note: requires additional types generated from: common.proto
// Note: requires additional types generated from: task.proto
// Note: requires additional types generated from: item.proto
namespace pomelo.player
{
  
  //---------------------------------------------------------------------------------------
  /// <summary>
  /// 玩家基本信息
  /// </summary>
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerBasic")]
  public partial class PlayerBasic : global::ProtoBuf.IExtensible
  {
    public PlayerBasic() {}
    
    
    private string _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string id
    {
      get { return _id; }
      set { _id = value; }
    }
    
    private string _name = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    
    private int _level = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int level
    {
      get { return _level; }
      set { _level = value; }
    }
    
    private int _pro = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"pro", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int pro
    {
      get { return _pro; }
      set { _pro = value; }
    }
    
    private int _upLevel = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"upLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int upLevel
    {
      get { return _upLevel; }
      set { _upLevel = value; }
    }
    
    private readonly global::System.Collections.Generic.List<pomelo.Avatar> _avatars = new global::System.Collections.Generic.List<pomelo.Avatar>();
    [global::ProtoBuf.ProtoMember(6, Name=@"avatars", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pomelo.Avatar> avatars
    {
      get { return _avatars; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Store")]
  public partial class Store : global::ProtoBuf.IExtensible
  {
    public Store() {}
    
    
    private readonly global::System.Collections.Generic.List<pomelo.item.Grid> _bagGrids = new global::System.Collections.Generic.List<pomelo.item.Grid>();
    [global::ProtoBuf.ProtoMember(1, Name=@"bagGrids", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pomelo.item.Grid> bagGrids
    {
      get { return _bagGrids; }
    }
  
    
    private int _bagGridCount = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"bagGridCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int bagGridCount
    {
      get { return _bagGridCount; }
      set { _bagGridCount = value; }
    }
    
    private int _bagTotalCount = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"bagTotalCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int bagTotalCount
    {
      get { return _bagTotalCount; }
      set { _bagTotalCount = value; }
    }
    
    private int _type = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    
    private int _gridPrice = default(int);
    /// <summary>
    /// 一个格子需要的钻石
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"gridPrice", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int gridPrice
    {
      get { return _gridPrice; }
      set { _gridPrice = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Stores")]
  public partial class Stores : global::ProtoBuf.IExtensible
  {
    public Stores() {}
    
    
    private pomelo.player.Store _bag = null;
    /// <summary>
    /// 背包
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"bag", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public pomelo.player.Store bag
    {
      get { return _bag; }
      set { _bag = value; }
    }
    
    private pomelo.player.Store _wareHouse = null;
    /// <summary>
    /// 仓库
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"wareHouse", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public pomelo.player.Store wareHouse
    {
      get { return _wareHouse; }
      set { _wareHouse = value; }
    }
    
    private pomelo.player.Store _recycle = null;
    /// <summary>
    /// 出售物品回收站
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"recycle", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public pomelo.player.Store recycle
    {
      get { return _recycle; }
      set { _recycle = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Equipments")]
  public partial class Equipments : global::ProtoBuf.IExtensible
  {
    public Equipments() {}
    
    
    private readonly global::System.Collections.Generic.List<pomelo.item.Grid> _equips = new global::System.Collections.Generic.List<pomelo.item.Grid>();
    [global::ProtoBuf.ProtoMember(1, Name=@"equips", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pomelo.item.Grid> equips
    {
      get { return _equips; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OfflineBaseData")]
  public partial class OfflineBaseData : global::ProtoBuf.IExtensible
  {
    public OfflineBaseData() {}
    
    
    private int _flag;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"flag", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int flag
    {
      get { return _flag; }
      set { _flag = value; }
    }
    
    private int _areaId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"areaId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int areaId
    {
      get { return _areaId; }
      set { _areaId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Attachment")]
  public partial class Attachment : global::ProtoBuf.IExtensible
  {
    public Attachment() {}
    
    
    private int _templateId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"templateId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int templateId
    {
      get { return _templateId; }
      set { _templateId = value; }
    }
    
    private int _icon;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"icon", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int icon
    {
      get { return _icon; }
      set { _icon = value; }
    }
    
    private int _num;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int num
    {
      get { return _num; }
      set { _num = value; }
    }
    
    private int _quality;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"quality", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int quality
    {
      get { return _quality; }
      set { _quality = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Mail")]
  public partial class Mail : global::ProtoBuf.IExtensible
  {
    public Mail() {}
    
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    
    private int _type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    
    private int _fromType;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"fromType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int fromType
    {
      get { return _fromType; }
      set { _fromType = value; }
    }
    
    private int _fromIcon;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"fromIcon", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int fromIcon
    {
      get { return _fromIcon; }
      set { _fromIcon = value; }
    }
    
    private string _fromName;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"fromName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string fromName
    {
      get { return _fromName; }
      set { _fromName = value; }
    }
    
    private string _title;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"title", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string title
    {
      get { return _title; }
      set { _title = value; }
    }
    
    private string _content;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"content", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string content
    {
      get { return _content; }
      set { _content = value; }
    }
    
    private string _createDate;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"createDate", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string createDate
    {
      get { return _createDate; }
      set { _createDate = value; }
    }
    
    private int _status;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int status
    {
      get { return _status; }
      set { _status = value; }
    }
    
    private readonly global::System.Collections.Generic.List<pomelo.player.Attachment> _attachment = new global::System.Collections.Generic.List<pomelo.player.Attachment>();
    [global::ProtoBuf.ProtoMember(10, Name=@"attachment", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pomelo.player.Attachment> attachment
    {
      get { return _attachment; }
    }
  
    
    private string _timeStamp;
    [global::ProtoBuf.ProtoMember(11, IsRequired = true, Name=@"timeStamp", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string timeStamp
    {
      get { return _timeStamp; }
      set { _timeStamp = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SetData")]
  public partial class SetData : global::ProtoBuf.IExtensible
  {
    public SetData() {}
    
    
    private int _recvMailSet;
    /// <summary>
    /// 接收邮件
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"recvMailSet", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int recvMailSet
    {
      get { return _recvMailSet; }
      set { _recvMailSet = value; }
    }
    
    private int _teamInviteSet;
    /// <summary>
    /// 允许组队邀请
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"teamInviteSet", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int teamInviteSet
    {
      get { return _teamInviteSet; }
      set { _teamInviteSet = value; }
    }
    
    private int _recvStrangerMsgSet;
    /// <summary>
    /// 允许接收陌生人消息
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"recvStrangerMsgSet", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int recvStrangerMsgSet
    {
      get { return _recvStrangerMsgSet; }
      set { _recvStrangerMsgSet = value; }
    }
    
    private int _recvAddFriendSet;
    /// <summary>
    /// 允许接收好友申请
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"recvAddFriendSet", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int recvAddFriendSet
    {
      get { return _recvAddFriendSet; }
      set { _recvAddFriendSet = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HookSetData")]
  public partial class HookSetData : global::ProtoBuf.IExtensible
  {
    public HookSetData() {}
    
    
    private int _hpPercent;
    /// <summary>
    /// 生命低于%
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"hpPercent", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int hpPercent
    {
      get { return _hpPercent; }
      set { _hpPercent = value; }
    }
    
    private int _mpPercent;
    /// <summary>
    /// 法力低于%
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"mpPercent", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int mpPercent
    {
      get { return _mpPercent; }
      set { _mpPercent = value; }
    }
    
    private string _hpItemCode;
    /// <summary>
    /// 生命药剂
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"hpItemCode", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string hpItemCode
    {
      get { return _hpItemCode; }
      set { _hpItemCode = value; }
    }
    
    private string _mpItemCode;
    /// <summary>
    /// 法力药剂
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"mpItemCode", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string mpItemCode
    {
      get { return _mpItemCode; }
      set { _mpItemCode = value; }
    }
    
    private int _pkSet;
    /// <summary>
    /// 防PK设置 0-自动反击 1-自动逃走
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"pkSet", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int pkSet
    {
      get { return _pkSet; }
      set { _pkSet = value; }
    }
    
    private readonly global::System.Collections.Generic.List<int> _meltQcolor = new global::System.Collections.Generic.List<int>();
    /// <summary>
    /// 熔炼装备颜色
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(6, Name=@"meltQcolor", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> meltQcolor
    {
      get { return _meltQcolor; }
    }
  
    
    private int _autoBuyHpItem = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"autoBuyHpItem", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int autoBuyHpItem
    {
      get { return _autoBuyHpItem; }
      set { _autoBuyHpItem = value; }
    }
    
    private int _autoBuyMpItem = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"autoBuyMpItem", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int autoBuyMpItem
    {
      get { return _autoBuyMpItem; }
      set { _autoBuyMpItem = value; }
    }
    
    private int _fieldMaphook;
    /// <summary>
    /// 野外全图挂机 0 不挂 1 挂
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"fieldMaphook", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int fieldMaphook
    {
      get { return _fieldMaphook; }
      set { _fieldMaphook = value; }
    }
    
    private int _areaMaphook;
    /// <summary>
    /// 其他场景全图挂机 0 不挂 1 挂
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"areaMaphook", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int areaMaphook
    {
      get { return _areaMaphook; }
      set { _areaMaphook = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FunctionInfo")]
  public partial class FunctionInfo : global::ProtoBuf.IExtensible
  {
    public FunctionInfo() {}
    
    
    private string _funcName = "";
    /// <summary>
    /// 功能名称
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"funcName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string funcName
    {
      get { return _funcName; }
      set { _funcName = value; }
    }
    
    private int _openFlag = default(int);
    /// <summary>
    /// 开启情况 0 未开启 1:开启
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"openFlag", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int openFlag
    {
      get { return _openFlag; }
      set { _openFlag = value; }
    }
    
    private int _playFlag = default(int);
    /// <summary>
    /// 开启后是否玩过
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"playFlag", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int playFlag
    {
      get { return _playFlag; }
      set { _playFlag = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Player")]
  public partial class Player : global::ProtoBuf.IExtensible
  {
    public Player() {}
    
    
    private string _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string id
    {
      get { return _id; }
      set { _id = value; }
    }
    
    private string _uid = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"uid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string uid
    {
      get { return _uid; }
      set { _uid = value; }
    }
    
    private string _name = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    
    private int _level = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int level
    {
      get { return _level; }
      set { _level = value; }
    }
    
    private long _exp = default(long);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"exp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long exp
    {
      get { return _exp; }
      set { _exp = value; }
    }
    
    private int _pro = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"pro", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int pro
    {
      get { return _pro; }
      set { _pro = value; }
    }
    
    private int _sp = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"sp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int sp
    {
      get { return _sp; }
      set { _sp = value; }
    }
    
    private int _upOrder = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"upOrder", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int upOrder
    {
      get { return _upOrder; }
      set { _upOrder = value; }
    }
    
    private int _classExp = default(int);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"classExp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int classExp
    {
      get { return _classExp; }
      set { _classExp = value; }
    }
    
    private long _gold = default(long);
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"gold", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long gold
    {
      get { return _gold; }
      set { _gold = value; }
    }
    
    private long _diamond = default(long);
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"diamond", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long diamond
    {
      get { return _diamond; }
      set { _diamond = value; }
    }
    
    private int _energy = default(int);
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"energy", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int energy
    {
      get { return _energy; }
      set { _energy = value; }
    }
    
    private int _vip = default(int);
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"vip", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int vip
    {
      get { return _vip; }
      set { _vip = value; }
    }
    
    private int _areaId = default(int);
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"areaId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int areaId
    {
      get { return _areaId; }
      set { _areaId = value; }
    }
    
    private int _hp = default(int);
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"hp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int hp
    {
      get { return _hp; }
      set { _hp = value; }
    }
    
    private int _mp = default(int);
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"mp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int mp
    {
      get { return _mp; }
      set { _mp = value; }
    }
    
    private int _needExp = default(int);
    [global::ProtoBuf.ProtoMember(20, IsRequired = false, Name=@"needExp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int needExp
    {
      get { return _needExp; }
      set { _needExp = value; }
    }
    
    private int _fightPower = default(int);
    [global::ProtoBuf.ProtoMember(21, IsRequired = false, Name=@"fightPower", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int fightPower
    {
      get { return _fightPower; }
      set { _fightPower = value; }
    }
    
    private pomelo.player.Stores _store = null;
    [global::ProtoBuf.ProtoMember(22, IsRequired = false, Name=@"store", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public pomelo.player.Stores store
    {
      get { return _store; }
      set { _store = value; }
    }
    
    private pomelo.player.Equipments _equipments = null;
    [global::ProtoBuf.ProtoMember(23, IsRequired = false, Name=@"equipments", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public pomelo.player.Equipments equipments
    {
      get { return _equipments; }
      set { _equipments = value; }
    }
    
    private pomelo.task.Tasks _tasks = null;
    [global::ProtoBuf.ProtoMember(24, IsRequired = false, Name=@"tasks", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public pomelo.task.Tasks tasks
    {
      get { return _tasks; }
      set { _tasks = value; }
    }
    
    private pomelo.player.OfflineBaseData _offlineBaseData = null;
    [global::ProtoBuf.ProtoMember(25, IsRequired = false, Name=@"offlineBaseData", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public pomelo.player.OfflineBaseData offlineBaseData
    {
      get { return _offlineBaseData; }
      set { _offlineBaseData = value; }
    }
    
    private pomelo.player.SetData _setData = null;
    /// <summary>
    /// optional Fashions fashions = 26;
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(27, IsRequired = false, Name=@"setData", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public pomelo.player.SetData setData
    {
      get { return _setData; }
      set { _setData = value; }
    }
    
    private int _prestige = default(int);
    [global::ProtoBuf.ProtoMember(29, IsRequired = false, Name=@"prestige", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int prestige
    {
      get { return _prestige; }
      set { _prestige = value; }
    }
    
    private int _juewei = default(int);
    [global::ProtoBuf.ProtoMember(30, IsRequired = false, Name=@"juewei", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int juewei
    {
      get { return _juewei; }
      set { _juewei = value; }
    }
    
    private readonly global::System.Collections.Generic.List<pomelo.SkillKeyStruct> _skillKeys = new global::System.Collections.Generic.List<pomelo.SkillKeyStruct>();
    [global::ProtoBuf.ProtoMember(31, Name=@"skillKeys", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pomelo.SkillKeyStruct> skillKeys
    {
      get { return _skillKeys; }
    }
  
    
    private pomelo.item.CountItems _countItems = null;
    [global::ProtoBuf.ProtoMember(32, IsRequired = false, Name=@"countItems", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public pomelo.item.CountItems countItems
    {
      get { return _countItems; }
      set { _countItems = value; }
    }
    
    private long _ticket = default(long);
    [global::ProtoBuf.ProtoMember(33, IsRequired = false, Name=@"ticket", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long ticket
    {
      get { return _ticket; }
      set { _ticket = value; }
    }
    
    private int _friendly = default(int);
    [global::ProtoBuf.ProtoMember(34, IsRequired = false, Name=@"friendly", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int friendly
    {
      get { return _friendly; }
      set { _friendly = value; }
    }
    
    private int _upLevel = default(int);
    [global::ProtoBuf.ProtoMember(35, IsRequired = false, Name=@"upLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int upLevel
    {
      get { return _upLevel; }
      set { _upLevel = value; }
    }
    
    private int _reqLevel = default(int);
    [global::ProtoBuf.ProtoMember(36, IsRequired = false, Name=@"reqLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int reqLevel
    {
      get { return _reqLevel; }
      set { _reqLevel = value; }
    }
    
    private int _pkModel = default(int);
    [global::ProtoBuf.ProtoMember(37, IsRequired = false, Name=@"pkModel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int pkModel
    {
      get { return _pkModel; }
      set { _pkModel = value; }
    }
    
    private int _pkValue = default(int);
    [global::ProtoBuf.ProtoMember(38, IsRequired = false, Name=@"pkValue", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int pkValue
    {
      get { return _pkValue; }
      set { _pkValue = value; }
    }
    
    private pomelo.player.HookSetData _hookSetData = null;
    [global::ProtoBuf.ProtoMember(39, IsRequired = false, Name=@"hookSetData", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public pomelo.player.HookSetData hookSetData
    {
      get { return _hookSetData; }
      set { _hookSetData = value; }
    }
    
    private string _zoneId = "";
    [global::ProtoBuf.ProtoMember(42, IsRequired = false, Name=@"zoneId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string zoneId
    {
      get { return _zoneId; }
      set { _zoneId = value; }
    }
    
    private int _solopoint = default(int);
    /// <summary>
    /// 宗师币
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(43, IsRequired = false, Name=@"solopoint", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int solopoint
    {
      get { return _solopoint; }
      set { _solopoint = value; }
    }
    
    private int _consumePoint = default(int);
    [global::ProtoBuf.ProtoMember(44, IsRequired = false, Name=@"consumePoint", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int consumePoint
    {
      get { return _consumePoint; }
      set { _consumePoint = value; }
    }
    
    private int _pawnGold = default(int);
    /// <summary>
    /// 工会仓库贡献
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(45, IsRequired = false, Name=@"pawnGold", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int pawnGold
    {
      get { return _pawnGold; }
      set { _pawnGold = value; }
    }
    
    private int _petPkModel = default(int);
    /// <summary>
    /// 宠物PK模式
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(46, IsRequired = false, Name=@"petPkModel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int petPkModel
    {
      get { return _petPkModel; }
      set { _petPkModel = value; }
    }
    
    private int _guildpoint = default(int);
    /// <summary>
    /// 副本积分
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(47, IsRequired = false, Name=@"guildpoint", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int guildpoint
    {
      get { return _guildpoint; }
      set { _guildpoint = value; }
    }
    
    private readonly global::System.Collections.Generic.List<pomelo.player.FunctionInfo> _functionList = new global::System.Collections.Generic.List<pomelo.player.FunctionInfo>();
    /// <summary>
    /// 功能开放列表
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(48, Name=@"functionList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pomelo.player.FunctionInfo> functionList
    {
      get { return _functionList; }
    }
  
    
    private readonly global::System.Collections.Generic.List<pomelo.KeyValueStruct> _clientConfig = new global::System.Collections.Generic.List<pomelo.KeyValueStruct>();
    [global::ProtoBuf.ProtoMember(49, Name=@"clientConfig", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pomelo.KeyValueStruct> clientConfig
    {
      get { return _clientConfig; }
    }
  
    
    private string _fightingPetId = "";
    /// <summary>
    /// 出战宠物id
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(50, IsRequired = false, Name=@"fightingPetId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string fightingPetId
    {
      get { return _fightingPetId; }
      set { _fightingPetId = value; }
    }
    
    private int _mapId = default(int);
    [global::ProtoBuf.ProtoMember(51, IsRequired = false, Name=@"mapId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int mapId
    {
      get { return _mapId; }
      set { _mapId = value; }
    }
    
    private string _instanceId = "";
    [global::ProtoBuf.ProtoMember(52, IsRequired = false, Name=@"instanceId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string instanceId
    {
      get { return _instanceId; }
      set { _instanceId = value; }
    }
    
    private int _treasurePoint = default(int);
    /// <summary>
    /// 君王宝藏积分
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(53, IsRequired = false, Name=@"treasurePoint", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int treasurePoint
    {
      get { return _treasurePoint; }
      set { _treasurePoint = value; }
    }
    
    private int _payGiftData = default(int);
    /// <summary>
    /// optional int32 dailySoulFinNum = 54;//炼魂今日完成次数 首充奖励领取信息，0没有充值 1已经首冲 2已经完成所有首冲
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(55, IsRequired = false, Name=@"payGiftData", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int payGiftData
    {
      get { return _payGiftData; }
      set { _payGiftData = value; }
    }
    
    private readonly global::System.Collections.Generic.List<string> _blackList = new global::System.Collections.Generic.List<string>();
    /// <summary>
    /// 黑名单
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(56, Name=@"blackList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> blackList
    {
      get { return _blackList; }
    }
  
    
    private readonly global::System.Collections.Generic.List<pomelo.item.EquipGridStrengthInfo> _strengthPos = new global::System.Collections.Generic.List<pomelo.item.EquipGridStrengthInfo>();
    /// <summary>
    /// 格子强化信息[索引-强化段位-强化等级]
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(57, Name=@"strengthPos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pomelo.item.EquipGridStrengthInfo> strengthPos
    {
      get { return _strengthPos; }
    }
  
    
    private string _guildId = "";
    /// <summary>
    /// 仙盟id
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(58, IsRequired = false, Name=@"guildId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string guildId
    {
      get { return _guildId; }
      set { _guildId = value; }
    }
    
    private int _guildPro = default(int);
    /// <summary>
    /// 仙盟职位
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(59, IsRequired = false, Name=@"guildPro", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int guildPro
    {
      get { return _guildPro; }
      set { _guildPro = value; }
    }
    
    private int _openMount = default(int);
    /// <summary>
    /// 1有坐骑，0没有
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(60, IsRequired = false, Name=@"openMount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int openMount
    {
      get { return _openMount; }
      set { _openMount = value; }
    }
    
    private readonly global::System.Collections.Generic.List<pomelo.item.EquipFashionInfo> _fashionInfo = new global::System.Collections.Generic.List<pomelo.item.EquipFashionInfo>();
    /// <summary>
    /// 时装信息
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(61, Name=@"fashionInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pomelo.item.EquipFashionInfo> fashionInfo
    {
      get { return _fashionInfo; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LookUpPlayer")]
  public partial class LookUpPlayer : global::ProtoBuf.IExtensible
  {
    public LookUpPlayer() {}
    
    
    private string _name = "";
    /// <summary>
    /// 名称
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    
    private int _level = default(int);
    /// <summary>
    /// 等级
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int level
    {
      get { return _level; }
      set { _level = value; }
    }
    
    private int _upLevel = default(int);
    /// <summary>
    /// 进阶等级
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"upLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int upLevel
    {
      get { return _upLevel; }
      set { _upLevel = value; }
    }
    
    private int _pro = default(int);
    /// <summary>
    /// 职业
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"pro", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int pro
    {
      get { return _pro; }
      set { _pro = value; }
    }
    
    private int _fightPower = default(int);
    /// <summary>
    /// 战斗力
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"fightPower", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int fightPower
    {
      get { return _fightPower; }
      set { _fightPower = value; }
    }
    
    private int _fightPowerRank = default(int);
    /// <summary>
    /// 战力排行
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"fightPowerRank", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int fightPowerRank
    {
      get { return _fightPowerRank; }
      set { _fightPowerRank = value; }
    }
    
    private int _juewei = default(int);
    /// <summary>
    /// 爵位
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"juewei", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int juewei
    {
      get { return _juewei; }
      set { _juewei = value; }
    }
    
    private int _titleId = default(int);
    /// <summary>
    /// 称号
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"titleId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int titleId
    {
      get { return _titleId; }
      set { _titleId = value; }
    }
    
    private string _guildName = "";
    /// <summary>
    /// 公会名
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"guildName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string guildName
    {
      get { return _guildName; }
      set { _guildName = value; }
    }
    
    private int _guildJob = default(int);
    /// <summary>
    /// 公会职位
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"guildJob", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int guildJob
    {
      get { return _guildJob; }
      set { _guildJob = value; }
    }
    
    private string _guildIcon = "";
    /// <summary>
    /// 公会icon
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"guildIcon", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string guildIcon
    {
      get { return _guildIcon; }
      set { _guildIcon = value; }
    }
    
    private readonly global::System.Collections.Generic.List<pomelo.item.ItemDetail> _equipments = new global::System.Collections.Generic.List<pomelo.item.ItemDetail>();
    /// <summary>
    /// 装备
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(12, Name=@"equipments", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pomelo.item.ItemDetail> equipments
    {
      get { return _equipments; }
    }
  
    
    private readonly global::System.Collections.Generic.List<pomelo.Avatar> _avatars = new global::System.Collections.Generic.List<pomelo.Avatar>();
    /// <summary>
    /// avatar 信息
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(13, Name=@"avatars", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pomelo.Avatar> avatars
    {
      get { return _avatars; }
    }
  
    
    private readonly global::System.Collections.Generic.List<pomelo.AttributeSimple> _attrs = new global::System.Collections.Generic.List<pomelo.AttributeSimple>();
    /// <summary>
    /// 战斗属性
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(14, Name=@"attrs", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pomelo.AttributeSimple> attrs
    {
      get { return _attrs; }
    }
  
    
    private int _upOrder = default(int);
    /// <summary>
    /// 境界
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"upOrder", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int upOrder
    {
      get { return _upOrder; }
      set { _upOrder = value; }
    }
    
    private int _pkValue = default(int);
    /// <summary>
    /// PK值
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"pkValue", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int pkValue
    {
      get { return _pkValue; }
      set { _pkValue = value; }
    }
    
    private readonly global::System.Collections.Generic.List<pomelo.item.EquipGridStrengthInfo> _strengthPos = new global::System.Collections.Generic.List<pomelo.item.EquipGridStrengthInfo>();
    /// <summary>
    /// 格子强化信息[索引-强化段位-强化等级]
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(17, Name=@"strengthPos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pomelo.item.EquipGridStrengthInfo> strengthPos
    {
      get { return _strengthPos; }
    }
  
    
    private long _exp = default(long);
    /// <summary>
    /// 经验
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"exp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long exp
    {
      get { return _exp; }
      set { _exp = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
}
  