//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// ***************************************************************************
// * 用途=资源副本
// ***************************************************************************

// Generated from: resourceDungeonHandler.proto
// Note: requires additional types generated from: item.proto
namespace pomelo.area
{
  
  //---------------------------------------------------------------------------------------
  /// <summary>
  /// 资源副本条目信息
  /// </summary>
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResourceDungeonInfo")]
  public partial class ResourceDungeonInfo : global::ProtoBuf.IExtensible
  {
    public ResourceDungeonInfo() {}
    
    
    private int _dungeonId;
    /// <summary>
    /// 副本ID
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"dungeonId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int dungeonId
    {
      get { return _dungeonId; }
      set { _dungeonId = value; }
    }
    
    private int _lastTimes;
    /// <summary>
    /// 当日剩余进入次数
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"lastTimes", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int lastTimes
    {
      get { return _lastTimes; }
      set { _lastTimes = value; }
    }
    
    private int _buyTimes = default(int);
    /// <summary>
    /// 当日已购买次数
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"buyTimes", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int buyTimes
    {
      get { return _buyTimes; }
      set { _buyTimes = value; }
    }
    
    private int _canBuyTimes = default(int);
    /// <summary>
    /// 当日可购买次数
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"canBuyTimes", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int canBuyTimes
    {
      get { return _canBuyTimes; }
      set { _canBuyTimes = value; }
    }
    
    private readonly global::System.Collections.Generic.List<pomelo.item.MiniItem> _awardItems = new global::System.Collections.Generic.List<pomelo.item.MiniItem>();
    /// <summary>
    /// 奖励预览
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(5, Name=@"awardItems", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pomelo.item.MiniItem> awardItems
    {
      get { return _awardItems; }
    }
  
    
    private bool _canSweep = default(bool);
    /// <summary>
    /// 能否扫荡
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"canSweep", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool canSweep
    {
      get { return _canSweep; }
      set { _canSweep = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  /// <summary>
  /// 获取资源副本信息
  /// </summary>
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"QueryResourceDugeonInfoRequest")]
  public partial class QueryResourceDugeonInfoRequest : global::ProtoBuf.IExtensible
  {
    public QueryResourceDugeonInfoRequest() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"QueryResourceDugeonInfoResponse")]
  public partial class QueryResourceDugeonInfoResponse : global::ProtoBuf.IExtensible
  {
    public QueryResourceDugeonInfoResponse() {}
    
    
    private int _s2c_code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"s2c_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int s2c_code
    {
      get { return _s2c_code; }
      set { _s2c_code = value; }
    }
    
    private string _s2c_msg = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"s2c_msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string s2c_msg
    {
      get { return _s2c_msg; }
      set { _s2c_msg = value; }
    }
    
    private readonly global::System.Collections.Generic.List<pomelo.area.ResourceDungeonInfo> _dungeons = new global::System.Collections.Generic.List<pomelo.area.ResourceDungeonInfo>();
    /// <summary>
    /// 当日剩余进入次数
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(3, Name=@"dungeons", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pomelo.area.ResourceDungeonInfo> dungeons
    {
      get { return _dungeons; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  /// <summary>
  /// 购买次数
  /// </summary>
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BuyTimesRequest")]
  public partial class BuyTimesRequest : global::ProtoBuf.IExtensible
  {
    public BuyTimesRequest() {}
    
    
    private int _dungeonId;
    /// <summary>
    /// 类型
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"dungeonId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int dungeonId
    {
      get { return _dungeonId; }
      set { _dungeonId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  /// <summary>
  /// 购买次数
  /// </summary>
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BuyTimesResponse")]
  public partial class BuyTimesResponse : global::ProtoBuf.IExtensible
  {
    public BuyTimesResponse() {}
    
    
    private int _s2c_code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"s2c_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int s2c_code
    {
      get { return _s2c_code; }
      set { _s2c_code = value; }
    }
    
    private string _s2c_msg = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"s2c_msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string s2c_msg
    {
      get { return _s2c_msg; }
      set { _s2c_msg = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  /// <summary>
  /// 进入资源副本
  /// </summary>
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EnterResourceDugeonInfoRequest")]
  public partial class EnterResourceDugeonInfoRequest : global::ProtoBuf.IExtensible
  {
    public EnterResourceDugeonInfoRequest() {}
    
    
    private int _dungeonId;
    /// <summary>
    /// 类型
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"dungeonId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int dungeonId
    {
      get { return _dungeonId; }
      set { _dungeonId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EnterResourceDugeonInfoResponse")]
  public partial class EnterResourceDugeonInfoResponse : global::ProtoBuf.IExtensible
  {
    public EnterResourceDugeonInfoResponse() {}
    
    
    private int _s2c_code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"s2c_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int s2c_code
    {
      get { return _s2c_code; }
      set { _s2c_code = value; }
    }
    
    private string _s2c_msg = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"s2c_msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string s2c_msg
    {
      get { return _s2c_msg; }
      set { _s2c_msg = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  /// <summary>
  /// 领取双倍奖励
  /// </summary>
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReceiveDoubleRewardRequest")]
  public partial class ReceiveDoubleRewardRequest : global::ProtoBuf.IExtensible
  {
    public ReceiveDoubleRewardRequest() {}
    
    
    private int _dungeonId;
    /// <summary>
    /// 类型
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"dungeonId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int dungeonId
    {
      get { return _dungeonId; }
      set { _dungeonId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReceiveDoubleRewardResponse")]
  public partial class ReceiveDoubleRewardResponse : global::ProtoBuf.IExtensible
  {
    public ReceiveDoubleRewardResponse() {}
    
    
    private int _s2c_code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"s2c_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int s2c_code
    {
      get { return _s2c_code; }
      set { _s2c_code = value; }
    }
    
    private string _s2c_msg = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"s2c_msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string s2c_msg
    {
      get { return _s2c_msg; }
      set { _s2c_msg = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  /// <summary>
  /// 资源副本倒计时请求
  /// </summary>
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResourceCountDownRequest")]
  public partial class ResourceCountDownRequest : global::ProtoBuf.IExtensible
  {
    public ResourceCountDownRequest() {}
    
    
    private int _dungeonId = default(int);
    /// <summary>
    /// 副本ID
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"dungeonId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int dungeonId
    {
      get { return _dungeonId; }
      set { _dungeonId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResourceCountDownResponse")]
  public partial class ResourceCountDownResponse : global::ProtoBuf.IExtensible
  {
    public ResourceCountDownResponse() {}
    
    
    private int _s2c_code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"s2c_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int s2c_code
    {
      get { return _s2c_code; }
      set { _s2c_code = value; }
    }
    
    private string _s2c_msg = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"s2c_msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string s2c_msg
    {
      get { return _s2c_msg; }
      set { _s2c_msg = value; }
    }
    
    private long _countDown = default(long);
    /// <summary>
    /// 剩余毫秒数
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"countDown", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long countDown
    {
      get { return _countDown; }
      set { _countDown = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  /// <summary>
  /// 扫荡请求
  /// </summary>
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResourceSweepRequest")]
  public partial class ResourceSweepRequest : global::ProtoBuf.IExtensible
  {
    public ResourceSweepRequest() {}
    
    
    private int _dungeonId;
    /// <summary>
    /// 类型
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"dungeonId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int dungeonId
    {
      get { return _dungeonId; }
      set { _dungeonId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  /// <summary>
  /// 扫荡响应
  /// </summary>
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResourceSweepResponse")]
  public partial class ResourceSweepResponse : global::ProtoBuf.IExtensible
  {
    public ResourceSweepResponse() {}
    
    
    private int _s2c_code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"s2c_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int s2c_code
    {
      get { return _s2c_code; }
      set { _s2c_code = value; }
    }
    
    private string _s2c_msg = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"s2c_msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string s2c_msg
    {
      get { return _s2c_msg; }
      set { _s2c_msg = value; }
    }
    
    private readonly global::System.Collections.Generic.List<pomelo.item.MiniItem> _awardItems = new global::System.Collections.Generic.List<pomelo.item.MiniItem>();
    /// <summary>
    /// 奖励
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(3, Name=@"awardItems", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pomelo.item.MiniItem> awardItems
    {
      get { return _awardItems; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
}
  