//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// ***************************************************************************
// * 作者= 张君俊
// * 创建时间= 2016-01-22
// * 用途= 购买和回购处理器
// ***************************************************************************

// Generated from: saleHandler.proto
// Note: requires additional types generated from: item.proto
namespace pomelo.area
{
  
  //---------------------------------------------------------------------------------------
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BuyItem")]
  public partial class BuyItem : global::ProtoBuf.IExtensible
  {
    public BuyItem() {}
    
    
    private int _typeId = default(int);
    /// <summary>
    /// 分类ID
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"typeId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int typeId
    {
      get { return _typeId; }
      set { _typeId = value; }
    }
    
    private int _itemId = default(int);
    /// <summary>
    /// 编号ID
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"itemId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int itemId
    {
      get { return _itemId; }
      set { _itemId = value; }
    }
    
    private string _itemShowName = "";
    /// <summary>
    /// 物品显示名称
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"itemShowName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string itemShowName
    {
      get { return _itemShowName; }
      set { _itemShowName = value; }
    }
    
    private pomelo.item.MiniItem _item = null;
    /// <summary>
    /// 物品信息
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"item", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public pomelo.item.MiniItem item
    {
      get { return _item; }
      set { _item = value; }
    }
    
    private int _moneyType = default(int);
    /// <summary>
    /// 货币类型 1.金币 2.金票 3.钻石
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"moneyType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int moneyType
    {
      get { return _moneyType; }
      set { _moneyType = value; }
    }
    
    private int _needMoney = default(int);
    /// <summary>
    /// 需要货币
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"needMoney", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int needMoney
    {
      get { return _needMoney; }
      set { _needMoney = value; }
    }
    
    private int _maxGroupCount = default(int);
    /// <summary>
    /// 最大堆叠数量 =1.不可叠加 >1.可以叠加
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"maxGroupCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int maxGroupCount
    {
      get { return _maxGroupCount; }
      set { _maxGroupCount = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SellGrid")]
  public partial class SellGrid : global::ProtoBuf.IExtensible
  {
    public SellGrid() {}
    
    
    private int _index;
    /// <summary>
    /// 格子索引
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int index
    {
      get { return _index; }
      set { _index = value; }
    }
    
    private int _num;
    /// <summary>
    /// 出售数量
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int num
    {
      get { return _num; }
      set { _num = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  /// <summary>
  /// 购买界面
  /// </summary>
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BuyPageRequest")]
  public partial class BuyPageRequest : global::ProtoBuf.IExtensible
  {
    public BuyPageRequest() {}
    
    
    private readonly global::System.Collections.Generic.List<int> _c2s_sellIndex = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(1, Name=@"c2s_sellIndex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> c2s_sellIndex
    {
      get { return _c2s_sellIndex; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BuyPageResponse")]
  public partial class BuyPageResponse : global::ProtoBuf.IExtensible
  {
    public BuyPageResponse() {}
    
    
    private int _s2c_code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"s2c_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int s2c_code
    {
      get { return _s2c_code; }
      set { _s2c_code = value; }
    }
    
    private string _s2c_msg = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"s2c_msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string s2c_msg
    {
      get { return _s2c_msg; }
      set { _s2c_msg = value; }
    }
    
    private readonly global::System.Collections.Generic.List<pomelo.area.BuyItem> _s2c_buyItems = new global::System.Collections.Generic.List<pomelo.area.BuyItem>();
    /// <summary>
    /// 购买物品列表
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(3, Name=@"s2c_buyItems", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pomelo.area.BuyItem> s2c_buyItems
    {
      get { return _s2c_buyItems; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  /// <summary>
  /// 购买
  /// </summary>
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BuyItemRequest")]
  public partial class BuyItemRequest : global::ProtoBuf.IExtensible
  {
    public BuyItemRequest() {}
    
    
    private int _c2s_typeId;
    /// <summary>
    /// 分类ID
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"c2s_typeId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int c2s_typeId
    {
      get { return _c2s_typeId; }
      set { _c2s_typeId = value; }
    }
    
    private int _c2s_itemId;
    /// <summary>
    /// 编号ID
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"c2s_itemId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int c2s_itemId
    {
      get { return _c2s_itemId; }
      set { _c2s_itemId = value; }
    }
    
    private int _c2s_num;
    /// <summary>
    /// 数量
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"c2s_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int c2s_num
    {
      get { return _c2s_num; }
      set { _c2s_num = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BuyItemResponse")]
  public partial class BuyItemResponse : global::ProtoBuf.IExtensible
  {
    public BuyItemResponse() {}
    
    
    private int _s2c_code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"s2c_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int s2c_code
    {
      get { return _s2c_code; }
      set { _s2c_code = value; }
    }
    
    private string _s2c_msg = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"s2c_msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string s2c_msg
    {
      get { return _s2c_msg; }
      set { _s2c_msg = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  /// <summary>
  /// 使用金币通过itemCode自动购买
  /// </summary>
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AutoBuyItemByCodeRequest")]
  public partial class AutoBuyItemByCodeRequest : global::ProtoBuf.IExtensible
  {
    public AutoBuyItemByCodeRequest() {}
    
    
    private readonly global::System.Collections.Generic.List<int> _c2s_typeId = new global::System.Collections.Generic.List<int>();
    /// <summary>
    /// 分类ID
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(1, Name=@"c2s_typeId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> c2s_typeId
    {
      get { return _c2s_typeId; }
    }
  
    
    private string _c2s_itemCode;
    /// <summary>
    /// 编号ID
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"c2s_itemCode", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string c2s_itemCode
    {
      get { return _c2s_itemCode; }
      set { _c2s_itemCode = value; }
    }
    
    private int _c2s_num;
    /// <summary>
    /// 数量
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"c2s_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int c2s_num
    {
      get { return _c2s_num; }
      set { _c2s_num = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AutoBuyItemByCodeResponse")]
  public partial class AutoBuyItemByCodeResponse : global::ProtoBuf.IExtensible
  {
    public AutoBuyItemByCodeResponse() {}
    
    
    private int _s2c_code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"s2c_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int s2c_code
    {
      get { return _s2c_code; }
      set { _s2c_code = value; }
    }
    
    private string _s2c_msg = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"s2c_msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string s2c_msg
    {
      get { return _s2c_msg; }
      set { _s2c_msg = value; }
    }
    
    private int _s2c_notEnoughGold = default(int);
    /// <summary>
    /// 是否金币不足 1:不足 0：足
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"s2c_notEnoughGold", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int s2c_notEnoughGold
    {
      get { return _s2c_notEnoughGold; }
      set { _s2c_notEnoughGold = value; }
    }
    
    private int _s2c_needGold = default(int);
    /// <summary>
    /// 需要金币
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"s2c_needGold", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int s2c_needGold
    {
      get { return _s2c_needGold; }
      set { _s2c_needGold = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  /// <summary>
  /// 出售
  /// </summary>
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SellItemsRequest")]
  public partial class SellItemsRequest : global::ProtoBuf.IExtensible
  {
    public SellItemsRequest() {}
    
    
    private readonly global::System.Collections.Generic.List<pomelo.area.SellGrid> _c2s_sellGrids = new global::System.Collections.Generic.List<pomelo.area.SellGrid>();
    /// <summary>
    /// 出售列表
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(1, Name=@"c2s_sellGrids", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pomelo.area.SellGrid> c2s_sellGrids
    {
      get { return _c2s_sellGrids; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SellItemsResponse")]
  public partial class SellItemsResponse : global::ProtoBuf.IExtensible
  {
    public SellItemsResponse() {}
    
    
    private int _s2c_code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"s2c_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int s2c_code
    {
      get { return _s2c_code; }
      set { _s2c_code = value; }
    }
    
    private string _s2c_msg = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"s2c_msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string s2c_msg
    {
      get { return _s2c_msg; }
      set { _s2c_msg = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  /// <summary>
  /// 回购
  /// </summary>
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RebuyItemRequest")]
  public partial class RebuyItemRequest : global::ProtoBuf.IExtensible
  {
    public RebuyItemRequest() {}
    
    
    private int _c2s_gridIndex;
    /// <summary>
    /// 格子索引
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"c2s_gridIndex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int c2s_gridIndex
    {
      get { return _c2s_gridIndex; }
      set { _c2s_gridIndex = value; }
    }
    
    private int _c2s_num;
    /// <summary>
    /// 数量
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"c2s_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int c2s_num
    {
      get { return _c2s_num; }
      set { _c2s_num = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RebuyItemResponse")]
  public partial class RebuyItemResponse : global::ProtoBuf.IExtensible
  {
    public RebuyItemResponse() {}
    
    
    private int _s2c_code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"s2c_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int s2c_code
    {
      get { return _s2c_code; }
      set { _s2c_code = value; }
    }
    
    private string _s2c_msg = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"s2c_msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string s2c_msg
    {
      get { return _s2c_msg; }
      set { _s2c_msg = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
}
  