//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// ***************************************************************************
// * 作者= 刘羿君
// * 创建时间= 2015-05-05
// * 用途= 商城处理器
// ***************************************************************************

// Generated from: shopMallHandler.proto
namespace pomelo.area
{
  
  //---------------------------------------------------------------------------------------
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MallItem")]
  public partial class MallItem : global::ProtoBuf.IExtensible
  {
    public MallItem() {}
    
    
    private string _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string id
    {
      get { return _id; }
      set { _id = value; }
    }
    
    private string _code;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"code", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string code
    {
      get { return _code; }
      set { _code = value; }
    }
    
    private int _groupCount;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"groupCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int groupCount
    {
      get { return _groupCount; }
      set { _groupCount = value; }
    }
    
    private int _originPrice;
    /// <summary>
    /// 原价
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"originPrice", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int originPrice
    {
      get { return _originPrice; }
      set { _originPrice = value; }
    }
    
    private int _nowPrice;
    /// <summary>
    /// 现价
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"nowPrice", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int nowPrice
    {
      get { return _nowPrice; }
      set { _nowPrice = value; }
    }
    
    private int _disCount;
    /// <summary>
    /// 折扣 -2.新品 -1.热销 0.无标签 >0.折扣
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"disCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int disCount
    {
      get { return _disCount; }
      set { _disCount = value; }
    }
    
    private int _endTime;
    /// <summary>
    /// 结束时间 非限时道具时间为0
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"endTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int endTime
    {
      get { return _endTime; }
      set { _endTime = value; }
    }
    
    private int _remainNum;
    /// <summary>
    /// 限购次数 -1.不限购 >=0.剩余次数
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"remainNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int remainNum
    {
      get { return _remainNum; }
      set { _remainNum = value; }
    }
    
    private int _consumeScore;
    /// <summary>
    /// 消费积分
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"consumeScore", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int consumeScore
    {
      get { return _consumeScore; }
      set { _consumeScore = value; }
    }
    
    private int _bindType;
    /// <summary>
    /// 0.不绑定 1.获得即绑定 2.装备后绑定
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"bindType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int bindType
    {
      get { return _bindType; }
      set { _bindType = value; }
    }
    
    private int _canSend;
    /// <summary>
    /// 1可以赠送 0不可以
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(11, IsRequired = true, Name=@"canSend", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int canSend
    {
      get { return _canSend; }
      set { _canSend = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MallScoreItem")]
  public partial class MallScoreItem : global::ProtoBuf.IExtensible
  {
    public MallScoreItem() {}
    
    
    private string _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string id
    {
      get { return _id; }
      set { _id = value; }
    }
    
    private string _code;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"code", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string code
    {
      get { return _code; }
      set { _code = value; }
    }
    
    private int _groupCount;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"groupCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int groupCount
    {
      get { return _groupCount; }
      set { _groupCount = value; }
    }
    
    private int _consumeScore;
    /// <summary>
    /// 消费积分
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"consumeScore", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int consumeScore
    {
      get { return _consumeScore; }
      set { _consumeScore = value; }
    }
    
    private int _isSellOut;
    /// <summary>
    /// 是否卖完 1.卖完 0.没卖完
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"isSellOut", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int isSellOut
    {
      get { return _isSellOut; }
      set { _isSellOut = value; }
    }
    
    private int _bindType;
    /// <summary>
    /// 0.不绑定 1.获得即绑定 2.装备后绑定
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"bindType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int bindType
    {
      get { return _bindType; }
      set { _bindType = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetMallItemListRequest")]
  public partial class GetMallItemListRequest : global::ProtoBuf.IExtensible
  {
    public GetMallItemListRequest() {}
    
    
    private int _c2s_moneyType;
    /// <summary>
    /// 1.钻石 2.金票
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"c2s_moneyType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int c2s_moneyType
    {
      get { return _c2s_moneyType; }
      set { _c2s_moneyType = value; }
    }
    
    private int _c2s_itemType;
    /// <summary>
    /// 1.限时 2.时装 3.坐骑 4.材料 5.消耗品 6.其他
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"c2s_itemType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int c2s_itemType
    {
      get { return _c2s_itemType; }
      set { _c2s_itemType = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetMallItemListResponse")]
  public partial class GetMallItemListResponse : global::ProtoBuf.IExtensible
  {
    public GetMallItemListResponse() {}
    
    
    private int _s2c_code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"s2c_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int s2c_code
    {
      get { return _s2c_code; }
      set { _s2c_code = value; }
    }
    
    private string _s2c_msg = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"s2c_msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string s2c_msg
    {
      get { return _s2c_msg; }
      set { _s2c_msg = value; }
    }
    
    private int _s2c_endTime = default(int);
    /// <summary>
    /// 结束时间 -1.限时标签关闭 0.限时活动时间未到 >0.限时活动开启
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"s2c_endTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int s2c_endTime
    {
      get { return _s2c_endTime; }
      set { _s2c_endTime = value; }
    }
    
    private readonly global::System.Collections.Generic.List<pomelo.area.MallItem> _s2c_items = new global::System.Collections.Generic.List<pomelo.area.MallItem>();
    [global::ProtoBuf.ProtoMember(4, Name=@"s2c_items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pomelo.area.MallItem> s2c_items
    {
      get { return _s2c_items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BuyMallItemRequest")]
  public partial class BuyMallItemRequest : global::ProtoBuf.IExtensible
  {
    public BuyMallItemRequest() {}
    
    
    private string _c2s_itemId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"c2s_itemId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string c2s_itemId
    {
      get { return _c2s_itemId; }
      set { _c2s_itemId = value; }
    }
    
    private int _c2s_count;
    /// <summary>
    /// 购买组数
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"c2s_count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int c2s_count
    {
      get { return _c2s_count; }
      set { _c2s_count = value; }
    }
    
    private string _c2s_playerId;
    /// <summary>
    /// 物品归属, 如果空字符串则为自己
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"c2s_playerId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string c2s_playerId
    {
      get { return _c2s_playerId; }
      set { _c2s_playerId = value; }
    }
    
    private int _c2s_bDiamond;
    /// <summary>
    /// 1：钻石购买，0：普通购买
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"c2s_bDiamond", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int c2s_bDiamond
    {
      get { return _c2s_bDiamond; }
      set { _c2s_bDiamond = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BuyMallItemResponse")]
  public partial class BuyMallItemResponse : global::ProtoBuf.IExtensible
  {
    public BuyMallItemResponse() {}
    
    
    private int _s2c_code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"s2c_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int s2c_code
    {
      get { return _s2c_code; }
      set { _s2c_code = value; }
    }
    
    private string _s2c_msg = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"s2c_msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string s2c_msg
    {
      get { return _s2c_msg; }
      set { _s2c_msg = value; }
    }
    
    private int _total_num = default(int);
    /// <summary>
    /// 该物品当前总数量
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"total_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int total_num
    {
      get { return _total_num; }
      set { _total_num = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetMallScoreItemListRequest")]
  public partial class GetMallScoreItemListRequest : global::ProtoBuf.IExtensible
  {
    public GetMallScoreItemListRequest() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetMallScoreItemListResponse")]
  public partial class GetMallScoreItemListResponse : global::ProtoBuf.IExtensible
  {
    public GetMallScoreItemListResponse() {}
    
    
    private int _s2c_code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"s2c_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int s2c_code
    {
      get { return _s2c_code; }
      set { _s2c_code = value; }
    }
    
    private string _s2c_msg = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"s2c_msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string s2c_msg
    {
      get { return _s2c_msg; }
      set { _s2c_msg = value; }
    }
    
    private readonly global::System.Collections.Generic.List<pomelo.area.MallScoreItem> _s2c_items = new global::System.Collections.Generic.List<pomelo.area.MallScoreItem>();
    [global::ProtoBuf.ProtoMember(3, Name=@"s2c_items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pomelo.area.MallScoreItem> s2c_items
    {
      get { return _s2c_items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BuyMallScoreItemRequest")]
  public partial class BuyMallScoreItemRequest : global::ProtoBuf.IExtensible
  {
    public BuyMallScoreItemRequest() {}
    
    
    private string _c2s_itemId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"c2s_itemId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string c2s_itemId
    {
      get { return _c2s_itemId; }
      set { _c2s_itemId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BuyMallScoreItemResponse")]
  public partial class BuyMallScoreItemResponse : global::ProtoBuf.IExtensible
  {
    public BuyMallScoreItemResponse() {}
    
    
    private int _s2c_code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"s2c_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int s2c_code
    {
      get { return _s2c_code; }
      set { _s2c_code = value; }
    }
    
    private string _s2c_msg = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"s2c_msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string s2c_msg
    {
      get { return _s2c_msg; }
      set { _s2c_msg = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MallTab")]
  public partial class MallTab : global::ProtoBuf.IExtensible
  {
    public MallTab() {}
    
    
    private int _moneyType;
    /// <summary>
    /// 1.钻石 2.金票
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"moneyType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int moneyType
    {
      get { return _moneyType; }
      set { _moneyType = value; }
    }
    
    private int _itemType;
    /// <summary>
    /// 1.限时 2.时装 3.坐骑 4.材料 5.消耗品 6.其他
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"itemType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int itemType
    {
      get { return _itemType; }
      set { _itemType = value; }
    }
    
    private int _isOpen;
    /// <summary>
    /// 1.开放 0.关闭
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"isOpen", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int isOpen
    {
      get { return _isOpen; }
      set { _isOpen = value; }
    }
    
    private string _name;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    
    private int _scriptNum;
    /// <summary>
    /// 红点信息
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"scriptNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int scriptNum
    {
      get { return _scriptNum; }
      set { _scriptNum = value; }
    }
    
    private int _isLimit;
    /// <summary>
    /// 是否是限時 1.是限時 0.不是限時
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"isLimit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int isLimit
    {
      get { return _isLimit; }
      set { _isLimit = value; }
    }
    
    private string _lastNumText = "";
    /// <summary>
    /// 道具剩余数量
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"lastNumText", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string lastNumText
    {
      get { return _lastNumText; }
      set { _lastNumText = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetMallTabsRequest")]
  public partial class GetMallTabsRequest : global::ProtoBuf.IExtensible
  {
    public GetMallTabsRequest() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetMallTabsResponse")]
  public partial class GetMallTabsResponse : global::ProtoBuf.IExtensible
  {
    public GetMallTabsResponse() {}
    
    
    private int _s2c_code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"s2c_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int s2c_code
    {
      get { return _s2c_code; }
      set { _s2c_code = value; }
    }
    
    private string _s2c_msg = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"s2c_msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string s2c_msg
    {
      get { return _s2c_msg; }
      set { _s2c_msg = value; }
    }
    
    private readonly global::System.Collections.Generic.List<pomelo.area.MallTab> _s2c_tabs = new global::System.Collections.Generic.List<pomelo.area.MallTab>();
    [global::ProtoBuf.ProtoMember(3, Name=@"s2c_tabs", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pomelo.area.MallTab> s2c_tabs
    {
      get { return _s2c_tabs; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
}
  