//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// ***************************************************************************
// * 作者= 张君俊
// * 创建时间= 2016-01-14
// * 用途= 进阶处理器
// ***************************************************************************

// Generated from: upLevelHandler.proto
// Note: requires additional types generated from: common.proto
namespace pomelo.area
{
  
  //---------------------------------------------------------------------------------------
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UpData")]
  public partial class UpData : global::ProtoBuf.IExtensible
  {
    public UpData() {}
    
    
    private int _level;
    /// <summary>
    /// 当前人物等级
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int level
    {
      get { return _level; }
      set { _level = value; }
    }
    
    private int _upLevel;
    /// <summary>
    /// 当前进阶等级
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"upLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int upLevel
    {
      get { return _upLevel; }
      set { _upLevel = value; }
    }
    
    private int _reqLevel;
    /// <summary>
    /// 要求人物等级
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"reqLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int reqLevel
    {
      get { return _reqLevel; }
      set { _reqLevel = value; }
    }
    
    private int _downLevel;
    /// <summary>
    /// 进阶后的人物等级
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"downLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int downLevel
    {
      get { return _downLevel; }
      set { _downLevel = value; }
    }
    
    private readonly global::System.Collections.Generic.List<pomelo.AttributeBase> _attrs = new global::System.Collections.Generic.List<pomelo.AttributeBase>();
    /// <summary>
    /// 进阶前后属性
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(5, Name=@"attrs", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pomelo.AttributeBase> attrs
    {
      get { return _attrs; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  /// <summary>
  /// 进阶界面
  /// </summary>
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UpInfoRequest")]
  public partial class UpInfoRequest : global::ProtoBuf.IExtensible
  {
    public UpInfoRequest() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UpInfoResponse")]
  public partial class UpInfoResponse : global::ProtoBuf.IExtensible
  {
    public UpInfoResponse() {}
    
    
    private int _s2c_code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"s2c_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int s2c_code
    {
      get { return _s2c_code; }
      set { _s2c_code = value; }
    }
    
    private string _s2c_msg = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"s2c_msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string s2c_msg
    {
      get { return _s2c_msg; }
      set { _s2c_msg = value; }
    }
    
    private pomelo.area.UpData _s2c_upData = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"s2c_upData", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public pomelo.area.UpData s2c_upData
    {
      get { return _s2c_upData; }
      set { _s2c_upData = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  /// <summary>
  /// 进阶
  /// </summary>
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UpLevelRequest")]
  public partial class UpLevelRequest : global::ProtoBuf.IExtensible
  {
    public UpLevelRequest() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UpLevelResponse")]
  public partial class UpLevelResponse : global::ProtoBuf.IExtensible
  {
    public UpLevelResponse() {}
    
    
    private int _s2c_code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"s2c_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int s2c_code
    {
      get { return _s2c_code; }
      set { _s2c_code = value; }
    }
    
    private string _s2c_msg = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"s2c_msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string s2c_msg
    {
      get { return _s2c_msg; }
      set { _s2c_msg = value; }
    }
    
    private int _s2c_hasNext = default(int);
    /// <summary>
    /// 是否有下一阶 0-无 1-有
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"s2c_hasNext", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int s2c_hasNext
    {
      get { return _s2c_hasNext; }
      set { _s2c_hasNext = value; }
    }
    
    private pomelo.area.UpData _s2c_upData = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"s2c_upData", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public pomelo.area.UpData s2c_upData
    {
      get { return _s2c_upData; }
      set { _s2c_upData = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
}
  