//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// ***************************************************************************
// * 作者= 卢松洁
// * 创建时间= 2015-08-27
// * 用途= 时装处理器
// ***************************************************************************

// Generated from: vipHandler.proto
namespace pomelo.area
{
  
  //---------------------------------------------------------------------------------------
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"VipRequest")]
  public partial class VipRequest : global::ProtoBuf.IExtensible
  {
    public VipRequest() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"VipGiftInfo")]
  public partial class VipGiftInfo : global::ProtoBuf.IExtensible
  {
    public VipGiftInfo() {}
    
    
    private int _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    
    private int _flag;
    /// <summary>
    /// 0表示没有领取过，1表示领取过了
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"flag", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int flag
    {
      get { return _flag; }
      set { _flag = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"VipGetGiftData")]
  public partial class VipGetGiftData : global::ProtoBuf.IExtensible
  {
    public VipGetGiftData() {}
    
    
    private readonly global::System.Collections.Generic.List<pomelo.area.VipGiftInfo> _datas = new global::System.Collections.Generic.List<pomelo.area.VipGiftInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"datas", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pomelo.area.VipGiftInfo> datas
    {
      get { return _datas; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"VipBuyGiftData")]
  public partial class VipBuyGiftData : global::ProtoBuf.IExtensible
  {
    public VipBuyGiftData() {}
    
    
    private int _vipLevel;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"vipLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int vipLevel
    {
      get { return _vipLevel; }
      set { _vipLevel = value; }
    }
    
    private int _dailyBuyCount;
    /// <summary>
    /// 当天购买次数
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"dailyBuyCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int dailyBuyCount
    {
      get { return _dailyBuyCount; }
      set { _dailyBuyCount = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"VipResponse")]
  public partial class VipResponse : global::ProtoBuf.IExtensible
  {
    public VipResponse() {}
    
    
    private int _s2c_code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"s2c_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int s2c_code
    {
      get { return _s2c_code; }
      set { _s2c_code = value; }
    }
    
    private string _s2c_msg = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"s2c_msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string s2c_msg
    {
      get { return _s2c_msg; }
      set { _s2c_msg = value; }
    }
    
    private readonly global::System.Collections.Generic.List<pomelo.area.VipGiftInfo> _datas = new global::System.Collections.Generic.List<pomelo.area.VipGiftInfo>();
    [global::ProtoBuf.ProtoMember(3, Name=@"datas", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pomelo.area.VipGiftInfo> datas
    {
      get { return _datas; }
    }
  
    
    private long _s2c_remainTime = default(long);
    /// <summary>
    /// vip剩余时间，秒
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"s2c_remainTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long s2c_remainTime
    {
      get { return _s2c_remainTime; }
      set { _s2c_remainTime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetEveryDayGiftRequest")]
  public partial class GetEveryDayGiftRequest : global::ProtoBuf.IExtensible
  {
    public GetEveryDayGiftRequest() {}
    
    
    private int _c2s_type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"c2s_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int c2s_type
    {
      get { return _c2s_type; }
      set { _c2s_type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetEveryDayGiftResponse")]
  public partial class GetEveryDayGiftResponse : global::ProtoBuf.IExtensible
  {
    public GetEveryDayGiftResponse() {}
    
    
    private int _s2c_code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"s2c_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int s2c_code
    {
      get { return _s2c_code; }
      set { _s2c_code = value; }
    }
    
    private string _s2c_msg = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"s2c_msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string s2c_msg
    {
      get { return _s2c_msg; }
      set { _s2c_msg = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BuyEveryDayGiftRequest")]
  public partial class BuyEveryDayGiftRequest : global::ProtoBuf.IExtensible
  {
    public BuyEveryDayGiftRequest() {}
    
    
    private int _c2s_vipLevel;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"c2s_vipLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int c2s_vipLevel
    {
      get { return _c2s_vipLevel; }
      set { _c2s_vipLevel = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BuyEveryDayGiftResponse")]
  public partial class BuyEveryDayGiftResponse : global::ProtoBuf.IExtensible
  {
    public BuyEveryDayGiftResponse() {}
    
    
    private int _s2c_code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"s2c_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int s2c_code
    {
      get { return _s2c_code; }
      set { _s2c_code = value; }
    }
    
    private string _s2c_msg = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"s2c_msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string s2c_msg
    {
      get { return _s2c_msg; }
      set { _s2c_msg = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BuyVipCardRequest")]
  public partial class BuyVipCardRequest : global::ProtoBuf.IExtensible
  {
    public BuyVipCardRequest() {}
    
    
    private int _c2s_typeId;
    /// <summary>
    /// 分类ID
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"c2s_typeId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int c2s_typeId
    {
      get { return _c2s_typeId; }
      set { _c2s_typeId = value; }
    }
    
    private int _c2s_itemId;
    /// <summary>
    /// 编号ID
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"c2s_itemId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int c2s_itemId
    {
      get { return _c2s_itemId; }
      set { _c2s_itemId = value; }
    }
    
    private int _c2s_type;
    /// <summary>
    /// 1 购买并使用 2 购买不使用
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"c2s_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int c2s_type
    {
      get { return _c2s_type; }
      set { _c2s_type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BuyVipCardResponse")]
  public partial class BuyVipCardResponse : global::ProtoBuf.IExtensible
  {
    public BuyVipCardResponse() {}
    
    
    private int _s2c_code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"s2c_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int s2c_code
    {
      get { return _s2c_code; }
      set { _s2c_code = value; }
    }
    
    private string _s2c_msg = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"s2c_msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string s2c_msg
    {
      get { return _s2c_msg; }
      set { _s2c_msg = value; }
    }
    
    private string _s2c_vipTime = "";
    /// <summary>
    /// vip到期时间戳
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"s2c_vipTime", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string s2c_vipTime
    {
      get { return _s2c_vipTime; }
      set { _s2c_vipTime = value; }
    }
    
    private readonly global::System.Collections.Generic.List<pomelo.area.VipGetGiftData> _s2c_getData = new global::System.Collections.Generic.List<pomelo.area.VipGetGiftData>();
    [global::ProtoBuf.ProtoMember(4, Name=@"s2c_getData", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pomelo.area.VipGetGiftData> s2c_getData
    {
      get { return _s2c_getData; }
    }
  
    
    private readonly global::System.Collections.Generic.List<pomelo.area.VipBuyGiftData> _s2c_buyData = new global::System.Collections.Generic.List<pomelo.area.VipBuyGiftData>();
    [global::ProtoBuf.ProtoMember(5, Name=@"s2c_buyData", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pomelo.area.VipBuyGiftData> s2c_buyData
    {
      get { return _s2c_buyData; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
}
  