//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// ***************************************************************************
// * 作者= 张君俊
// * 创建时间= 2016-01-07
// * 用途= 翅膀处理器
// ***************************************************************************

// Generated from: wingHandler.proto
// Note: requires additional types generated from: common.proto
namespace pomelo.area
{
  
  //---------------------------------------------------------------------------------------
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"WingData")]
  public partial class WingData : global::ProtoBuf.IExtensible
  {
    public WingData() {}
    
    
    private int _currLevel;
    /// <summary>
    /// 当前品阶
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"currLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int currLevel
    {
      get { return _currLevel; }
      set { _currLevel = value; }
    }
    
    private int _currStar;
    /// <summary>
    /// 当前星数
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"currStar", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int currStar
    {
      get { return _currStar; }
      set { _currStar = value; }
    }
    
    private int _currExp;
    /// <summary>
    /// 当前经验
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"currExp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int currExp
    {
      get { return _currExp; }
      set { _currExp = value; }
    }
    
    private int _currReiki;
    /// <summary>
    /// 当前灵气
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"currReiki", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int currReiki
    {
      get { return _currReiki; }
      set { _currReiki = value; }
    }
    
    private int _fightPower;
    /// <summary>
    /// 当前战力
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"fightPower", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int fightPower
    {
      get { return _fightPower; }
      set { _fightPower = value; }
    }
    
    private int _savedLevel = default(int);
    /// <summary>
    /// 保存品阶
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"savedLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int savedLevel
    {
      get { return _savedLevel; }
      set { _savedLevel = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  /// <summary>
  /// 获取翅膀信息
  /// </summary>
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetWingInfoRequest")]
  public partial class GetWingInfoRequest : global::ProtoBuf.IExtensible
  {
    public GetWingInfoRequest() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetWingInfoResponse")]
  public partial class GetWingInfoResponse : global::ProtoBuf.IExtensible
  {
    public GetWingInfoResponse() {}
    
    
    private int _s2c_code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"s2c_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int s2c_code
    {
      get { return _s2c_code; }
      set { _s2c_code = value; }
    }
    
    private string _s2c_msg = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"s2c_msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string s2c_msg
    {
      get { return _s2c_msg; }
      set { _s2c_msg = value; }
    }
    
    private pomelo.area.WingData _s2c_wingData = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"s2c_wingData", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public pomelo.area.WingData s2c_wingData
    {
      get { return _s2c_wingData; }
      set { _s2c_wingData = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  /// <summary>
  /// 培养翅膀
  /// </summary>
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TrainingWingRequest")]
  public partial class TrainingWingRequest : global::ProtoBuf.IExtensible
  {
    public TrainingWingRequest() {}
    
    
    private int _c2s_type;
    /// <summary>
    /// 1.灵气培养 2.道具培养
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"c2s_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int c2s_type
    {
      get { return _c2s_type; }
      set { _c2s_type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TrainingWingResponse")]
  public partial class TrainingWingResponse : global::ProtoBuf.IExtensible
  {
    public TrainingWingResponse() {}
    
    
    private int _s2c_code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"s2c_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int s2c_code
    {
      get { return _s2c_code; }
      set { _s2c_code = value; }
    }
    
    private string _s2c_msg = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"s2c_msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string s2c_msg
    {
      get { return _s2c_msg; }
      set { _s2c_msg = value; }
    }
    
    private pomelo.area.WingData _s2c_wingData = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"s2c_wingData", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public pomelo.area.WingData s2c_wingData
    {
      get { return _s2c_wingData; }
      set { _s2c_wingData = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
  //---------------------------------------------------------------------------------------
  /// <summary>
  /// 保存翅膀
  /// </summary>
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SaveWingNotify")]
  public partial class SaveWingNotify : global::ProtoBuf.IExtensible
  {
    public SaveWingNotify() {}
    
    
    private int _c2s_wingLevel;
    /// <summary>
    /// 翅膀品阶
    /// </summary>
    
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"c2s_wingLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int c2s_wingLevel
    {
      get { return _c2s_wingLevel; }
      set { _c2s_wingLevel = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  
}
  